-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qpsk_hls_top_addsub_0_0_ap_fixed_43_4_5_3_0_ap_fixed_43_4_5_3_0_ap_uint_1_s is
port (
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (42 downto 0);
    b : IN STD_LOGIC_VECTOR (42 downto 0);
    add : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (42 downto 0) );
end;


architecture behav of qpsk_hls_top_addsub_0_0_ap_fixed_43_4_5_3_0_ap_fixed_43_4_5_3_0_ap_uint_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal ret_V_5_fu_40_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal ret_V_fu_34_p2 : STD_LOGIC_VECTOR (42 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        ret_V_5_fu_40_p2 when (add(0) = '1') else 
        ret_V_fu_34_p2;
    ret_V_5_fu_40_p2 <= std_logic_vector(unsigned(b) + unsigned(a));
    ret_V_fu_34_p2 <= std_logic_vector(unsigned(a) - unsigned(b));
end behav;
