// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_qpsk_hls_top_Pipeline_XCORR_LOOP_DOT_PROD_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        peak_idx_2_out,
        peak_idx_2_out_ap_vld,
        g_matched_filter_template_q_address0,
        g_matched_filter_template_q_ce0,
        g_matched_filter_template_q_q0,
        g_matched_filter_template_i_address0,
        g_matched_filter_template_i_ce0,
        g_matched_filter_template_i_q0,
        g_baseband_data_q_address0,
        g_baseband_data_q_ce0,
        g_baseband_data_q_q0,
        g_baseband_data_i_address0,
        g_baseband_data_i_ce0,
        g_baseband_data_i_q0,
        grp_fu_814_p_din0,
        grp_fu_814_p_din1,
        grp_fu_814_p_opcode,
        grp_fu_814_p_dout0,
        grp_fu_814_p_ce,
        grp_fu_818_p_din0,
        grp_fu_818_p_din1,
        grp_fu_818_p_opcode,
        grp_fu_818_p_dout0,
        grp_fu_818_p_ce,
        grp_fu_806_p_din0,
        grp_fu_806_p_din1,
        grp_fu_806_p_dout0,
        grp_fu_806_p_ce,
        grp_fu_826_p_din0,
        grp_fu_826_p_din1,
        grp_fu_826_p_dout0,
        grp_fu_826_p_ce,
        grp_fu_509_p_din0,
        grp_fu_509_p_din1,
        grp_fu_509_p_opcode,
        grp_fu_509_p_dout0,
        grp_fu_509_p_ce,
        grp_fu_830_p_din0,
        grp_fu_830_p_din1,
        grp_fu_830_p_dout0,
        grp_fu_830_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] peak_idx_2_out;
output   peak_idx_2_out_ap_vld;
output  [11:0] g_matched_filter_template_q_address0;
output   g_matched_filter_template_q_ce0;
input  [31:0] g_matched_filter_template_q_q0;
output  [11:0] g_matched_filter_template_i_address0;
output   g_matched_filter_template_i_ce0;
input  [31:0] g_matched_filter_template_i_q0;
output  [13:0] g_baseband_data_q_address0;
output   g_baseband_data_q_ce0;
input  [31:0] g_baseband_data_q_q0;
output  [13:0] g_baseband_data_i_address0;
output   g_baseband_data_i_ce0;
input  [31:0] g_baseband_data_i_q0;
output  [31:0] grp_fu_814_p_din0;
output  [31:0] grp_fu_814_p_din1;
output  [1:0] grp_fu_814_p_opcode;
input  [31:0] grp_fu_814_p_dout0;
output   grp_fu_814_p_ce;
output  [31:0] grp_fu_818_p_din0;
output  [31:0] grp_fu_818_p_din1;
output  [0:0] grp_fu_818_p_opcode;
input  [31:0] grp_fu_818_p_dout0;
output   grp_fu_818_p_ce;
output  [31:0] grp_fu_806_p_din0;
output  [31:0] grp_fu_806_p_din1;
input  [31:0] grp_fu_806_p_dout0;
output   grp_fu_806_p_ce;
output  [31:0] grp_fu_826_p_din0;
output  [31:0] grp_fu_826_p_din1;
input  [31:0] grp_fu_826_p_dout0;
output   grp_fu_826_p_ce;
output  [31:0] grp_fu_509_p_din0;
output  [31:0] grp_fu_509_p_din1;
output  [4:0] grp_fu_509_p_opcode;
input  [0:0] grp_fu_509_p_dout0;
output   grp_fu_509_p_ce;
output  [31:0] grp_fu_830_p_din0;
output  [31:0] grp_fu_830_p_din1;
input  [31:0] grp_fu_830_p_dout0;
output   grp_fu_830_p_ce;

reg ap_idle;
reg peak_idx_2_out_ap_vld;
reg g_matched_filter_template_q_ce0;
reg g_matched_filter_template_i_ce0;
reg g_baseband_data_q_ce0;
reg g_baseband_data_i_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state10_pp0_stage4_iter1;
wire    ap_block_state15_pp0_stage4_iter2;
wire    ap_block_state20_pp0_stage4_iter3;
wire    ap_block_state25_pp0_stage4_iter4;
wire    ap_block_state30_pp0_stage4_iter5;
wire    ap_block_state35_pp0_stage4_iter6;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln132_reg_540;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_174;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state12_pp0_stage1_iter2;
wire    ap_block_state17_pp0_stage1_iter3;
wire    ap_block_state22_pp0_stage1_iter4;
wire    ap_block_state27_pp0_stage1_iter5;
wire    ap_block_state32_pp0_stage1_iter6;
wire    ap_block_state37_pp0_stage1_iter7;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln132_reg_540_pp0_iter2_reg;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state13_pp0_stage2_iter2;
wire    ap_block_state18_pp0_stage2_iter3;
wire    ap_block_state23_pp0_stage2_iter4;
wire    ap_block_state28_pp0_stage2_iter5;
wire    ap_block_state33_pp0_stage2_iter6;
wire    ap_block_state38_pp0_stage2_iter7;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] icmp_ln132_reg_540_pp0_iter3_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
wire    ap_block_state16_pp0_stage0_iter3;
wire    ap_block_state21_pp0_stage0_iter4;
wire    ap_block_state26_pp0_stage0_iter5;
wire    ap_block_state31_pp0_stage0_iter6;
wire    ap_block_state36_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [12:0] lag_reg_535;
reg   [12:0] lag_reg_535_pp0_iter1_reg;
reg   [12:0] lag_reg_535_pp0_iter2_reg;
reg   [12:0] lag_reg_535_pp0_iter3_reg;
reg   [12:0] lag_reg_535_pp0_iter4_reg;
reg   [12:0] lag_reg_535_pp0_iter5_reg;
reg   [12:0] lag_reg_535_pp0_iter6_reg;
reg   [12:0] lag_reg_535_pp0_iter7_reg;
wire   [0:0] icmp_ln132_fu_219_p2;
reg   [0:0] icmp_ln132_reg_540_pp0_iter1_reg;
reg   [0:0] icmp_ln132_reg_540_pp0_iter4_reg;
reg   [0:0] icmp_ln132_reg_540_pp0_iter5_reg;
reg   [0:0] icmp_ln132_reg_540_pp0_iter6_reg;
reg   [0:0] icmp_ln132_reg_540_pp0_iter7_reg;
wire   [0:0] icmp_ln134_fu_234_p2;
reg   [0:0] icmp_ln134_reg_544;
reg   [0:0] icmp_ln134_reg_544_pp0_iter1_reg;
reg   [0:0] icmp_ln134_reg_544_pp0_iter2_reg;
reg   [0:0] icmp_ln134_reg_544_pp0_iter3_reg;
reg   [0:0] icmp_ln134_reg_544_pp0_iter4_reg;
reg   [0:0] icmp_ln134_reg_544_pp0_iter5_reg;
reg   [0:0] icmp_ln134_reg_544_pp0_iter6_reg;
reg   [0:0] icmp_ln134_reg_544_pp0_iter7_reg;
reg   [31:0] a_q_2_reg_572;
reg   [31:0] a_i_5_reg_577;
reg   [31:0] a_q_3_reg_583;
reg   [31:0] a_i_3_reg_588;
wire   [31:0] b_q_fu_318_p1;
reg   [31:0] b_q_reg_593;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state14_pp0_stage3_iter2;
wire    ap_block_state19_pp0_stage3_iter3;
wire    ap_block_state24_pp0_stage3_iter4;
wire    ap_block_state29_pp0_stage3_iter5;
wire    ap_block_state34_pp0_stage3_iter6;
wire    ap_block_state39_pp0_stage3_iter7;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] mul_i3_reg_599;
reg   [31:0] mul4_i1_reg_604;
reg   [31:0] mul8_i1_reg_609;
reg   [31:0] mul11_i1_reg_614;
reg   [31:0] b_i_1_reg_619;
wire   [31:0] select_ln132_1_fu_328_p3;
reg   [31:0] b_q_1_reg_635;
reg   [31:0] dot_prod_q_1_reg_640;
wire   [31:0] select_ln132_2_fu_339_p3;
reg   [31:0] mul_i2_dup_reg_651;
reg   [31:0] mul3_i1_dup_reg_656;
reg   [31:0] add_i2_dup_reg_661;
reg   [31:0] corr_abs_reg_666;
reg   [31:0] max_corr_val_1_reg_673;
wire   [31:0] select_ln132_5_fu_470_p3;
reg   [31:0] select_ln132_5_reg_681;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage2_subdone;
reg    ap_condition_exit_pp0_iter7_stage2;
wire    ap_block_pp0_stage3_subdone;
wire   [63:0] zext_ln136_fu_282_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] n_cast11_fu_266_p1;
reg   [31:0] a_q_fu_62;
reg   [31:0] ap_sig_allocacmp_dot_prod_q_1;
wire    ap_block_pp0_stage3;
wire    ap_loop_init;
reg   [31:0] a_i_fu_66;
reg   [31:0] ap_sig_allocacmp_dot_prod_i_1;
wire    ap_block_pp0_stage2;
reg   [12:0] n_fu_70;
wire   [12:0] add_ln134_fu_288_p2;
reg   [31:0] peak_idx_fu_74;
reg   [31:0] max_corr_val_fu_78;
wire   [31:0] select_ln132_4_fu_464_p3;
reg   [12:0] peak_idx_1_fu_82;
wire   [12:0] select_ln132_3_fu_254_p3;
reg   [24:0] indvar_flatten_fu_86;
wire   [24:0] add_ln132_fu_225_p2;
wire   [31:0] peak_idx_5_fu_449_p3;
wire    ap_block_pp0_stage2_01001;
wire    ap_block_pp0_stage0;
reg   [31:0] grp_fu_149_p0;
reg   [31:0] grp_fu_149_p1;
wire    ap_block_pp0_stage4;
reg   [31:0] grp_fu_153_p0;
reg   [31:0] grp_fu_153_p1;
reg   [31:0] grp_fu_157_p0;
reg   [31:0] grp_fu_157_p1;
reg   [31:0] grp_fu_161_p1;
wire   [12:0] add_ln132_1_fu_248_p2;
wire   [12:0] select_ln132_fu_240_p3;
wire   [13:0] n_cast_fu_272_p1;
wire   [13:0] zext_ln132_fu_262_p1;
wire   [13:0] add_ln136_fu_276_p2;
wire   [31:0] bitcast_ln14_fu_309_p1;
wire   [31:0] xor_ln14_fu_312_p2;
wire   [31:0] bitcast_ln140_fu_364_p1;
wire   [31:0] bitcast_ln140_1_fu_381_p1;
wire   [7:0] tmp_13_dup_fu_367_p4;
wire   [22:0] trunc_ln140_fu_377_p1;
wire   [0:0] icmp_ln140_1_fu_404_p2;
wire   [0:0] icmp_ln140_fu_398_p2;
wire   [7:0] tmp_14_dup_fu_384_p4;
wire   [22:0] trunc_ln140_1_fu_394_p1;
wire   [0:0] icmp_ln140_3_fu_422_p2;
wire   [0:0] icmp_ln140_2_fu_416_p2;
wire   [0:0] or_ln140_fu_410_p2;
wire   [0:0] or_ln140_1_fu_428_p2;
wire   [0:0] and_ln140_fu_434_p2;
wire   [0:0] and_ln140_1_fu_440_p2;
wire   [31:0] zext_ln140_fu_446_p1;
wire   [31:0] select_ln140_fu_458_p3;
reg   [1:0] grp_fu_149_opcode;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage4_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage4_11001;
reg    ap_idle_pp0_0to6;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to7;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

qpsk_hls_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) | ((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_i_fu_66 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln132_reg_540_pp0_iter3_reg == 1'd0))) begin
        a_i_fu_66 <= reg_174;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_q_fu_62 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln132_reg_540_pp0_iter3_reg == 1'd0))) begin
        a_q_fu_62 <= reg_174;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2)) | ((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_86 <= 25'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln132_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten_fu_86 <= add_ln132_fu_225_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_corr_val_fu_78 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln132_reg_540_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        max_corr_val_fu_78 <= select_ln132_4_fu_464_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        n_fu_70 <= 13'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln132_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        n_fu_70 <= add_ln134_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        peak_idx_1_fu_82 <= 13'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln132_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        peak_idx_1_fu_82 <= select_ln132_3_fu_254_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        peak_idx_fu_74 <= 32'd4294967295;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln132_reg_540_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        peak_idx_fu_74 <= select_ln132_5_reg_681;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_reg_540 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_i_3_reg_588 <= g_baseband_data_i_q0;
        a_i_5_reg_577 <= g_matched_filter_template_i_q0;
        a_q_2_reg_572 <= g_matched_filter_template_q_q0;
        a_q_3_reg_583 <= g_baseband_data_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_i2_dup_reg_661 <= grp_fu_814_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln132_reg_540_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_i_1_reg_619 <= grp_fu_814_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln132_reg_540_pp0_iter2_reg == 1'd0))) begin
        b_q_1_reg_635 <= grp_fu_814_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_reg_540 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        b_q_reg_593 <= b_q_fu_318_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        corr_abs_reg_666 <= grp_fu_830_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dot_prod_q_1_reg_640 <= ap_sig_allocacmp_dot_prod_q_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln132_reg_540 <= icmp_ln132_fu_219_p2;
        icmp_ln132_reg_540_pp0_iter1_reg <= icmp_ln132_reg_540;
        icmp_ln132_reg_540_pp0_iter2_reg <= icmp_ln132_reg_540_pp0_iter1_reg;
        icmp_ln132_reg_540_pp0_iter3_reg <= icmp_ln132_reg_540_pp0_iter2_reg;
        icmp_ln132_reg_540_pp0_iter4_reg <= icmp_ln132_reg_540_pp0_iter3_reg;
        icmp_ln132_reg_540_pp0_iter5_reg <= icmp_ln132_reg_540_pp0_iter4_reg;
        icmp_ln132_reg_540_pp0_iter6_reg <= icmp_ln132_reg_540_pp0_iter5_reg;
        icmp_ln132_reg_540_pp0_iter7_reg <= icmp_ln132_reg_540_pp0_iter6_reg;
        icmp_ln134_reg_544_pp0_iter1_reg <= icmp_ln134_reg_544;
        icmp_ln134_reg_544_pp0_iter2_reg <= icmp_ln134_reg_544_pp0_iter1_reg;
        icmp_ln134_reg_544_pp0_iter3_reg <= icmp_ln134_reg_544_pp0_iter2_reg;
        icmp_ln134_reg_544_pp0_iter4_reg <= icmp_ln134_reg_544_pp0_iter3_reg;
        icmp_ln134_reg_544_pp0_iter5_reg <= icmp_ln134_reg_544_pp0_iter4_reg;
        icmp_ln134_reg_544_pp0_iter6_reg <= icmp_ln134_reg_544_pp0_iter5_reg;
        icmp_ln134_reg_544_pp0_iter7_reg <= icmp_ln134_reg_544_pp0_iter6_reg;
        lag_reg_535 <= peak_idx_1_fu_82;
        lag_reg_535_pp0_iter1_reg <= lag_reg_535;
        lag_reg_535_pp0_iter2_reg <= lag_reg_535_pp0_iter1_reg;
        lag_reg_535_pp0_iter3_reg <= lag_reg_535_pp0_iter2_reg;
        lag_reg_535_pp0_iter4_reg <= lag_reg_535_pp0_iter3_reg;
        lag_reg_535_pp0_iter5_reg <= lag_reg_535_pp0_iter4_reg;
        lag_reg_535_pp0_iter6_reg <= lag_reg_535_pp0_iter5_reg;
        lag_reg_535_pp0_iter7_reg <= lag_reg_535_pp0_iter6_reg;
        max_corr_val_1_reg_673 <= max_corr_val_fu_78;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln132_fu_219_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln134_reg_544 <= icmp_ln134_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_540_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul11_i1_reg_614 <= grp_fu_826_p_dout0;
        mul8_i1_reg_609 <= grp_fu_806_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul3_i1_dup_reg_656 <= grp_fu_806_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln132_reg_540 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul4_i1_reg_604 <= grp_fu_826_p_dout0;
        mul_i3_reg_599 <= grp_fu_806_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_i2_dup_reg_651 <= grp_fu_806_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln132_reg_540_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln132_reg_540_pp0_iter2_reg == 1'd0)))) begin
        reg_174 <= grp_fu_818_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln132_reg_540_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        select_ln132_5_reg_681 <= select_ln132_5_fu_470_p3;
    end
end

always @ (*) begin
    if (((icmp_ln132_reg_540 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln132_reg_540_pp0_iter7_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter7_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter7_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to7 = 1'b1;
    end else begin
        ap_idle_pp0_1to7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln132_reg_540_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_dot_prod_i_1 = reg_174;
    end else begin
        ap_sig_allocacmp_dot_prod_i_1 = a_i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln132_reg_540_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_dot_prod_q_1 = reg_174;
    end else begin
        ap_sig_allocacmp_dot_prod_q_1 = a_q_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_baseband_data_i_ce0 = 1'b1;
    end else begin
        g_baseband_data_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_baseband_data_q_ce0 = 1'b1;
    end else begin
        g_baseband_data_q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_i_ce0 = 1'b1;
    end else begin
        g_matched_filter_template_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_q_ce0 = 1'b1;
    end else begin
        g_matched_filter_template_q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_540_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_149_opcode = 2'd1;
    end else if ((((1'b0 == ap_block_pp0_stage4_00001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_540_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_149_opcode = 2'd0;
    end else begin
        grp_fu_149_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_149_p0 = mul_i2_dup_reg_651;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_149_p0 = mul8_i1_reg_609;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_149_p0 = mul_i3_reg_599;
    end else begin
        grp_fu_149_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_149_p1 = mul3_i1_dup_reg_656;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_149_p1 = mul11_i1_reg_614;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_149_p1 = mul4_i1_reg_604;
    end else begin
        grp_fu_149_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_153_p0 = select_ln132_2_fu_339_p3;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_153_p0 = select_ln132_1_fu_328_p3;
        end else begin
            grp_fu_153_p0 = 'bx;
        end
    end else begin
        grp_fu_153_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_153_p1 = b_q_1_reg_635;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_153_p1 = b_i_1_reg_619;
        end else begin
            grp_fu_153_p1 = 'bx;
        end
    end else begin
        grp_fu_153_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_157_p0 = dot_prod_q_1_reg_640;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_157_p0 = ap_sig_allocacmp_dot_prod_i_1;
    end else if ((((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_157_p0 = a_i_3_reg_588;
    end else begin
        grp_fu_157_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_157_p1 = dot_prod_q_1_reg_640;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_157_p1 = ap_sig_allocacmp_dot_prod_i_1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_157_p1 = b_q_reg_593;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_157_p1 = a_i_5_reg_577;
    end else begin
        grp_fu_157_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_161_p1 = a_i_5_reg_577;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_161_p1 = b_q_fu_318_p1;
        end else begin
            grp_fu_161_p1 = 'bx;
        end
    end else begin
        grp_fu_161_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln132_reg_540_pp0_iter7_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        peak_idx_2_out_ap_vld = 1'b1;
    end else begin
        peak_idx_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to7 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_idle_pp0_0to6 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter7_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln132_1_fu_248_p2 = (peak_idx_1_fu_82 + 13'd1);

assign add_ln132_fu_225_p2 = (indvar_flatten_fu_86 + 25'd1);

assign add_ln134_fu_288_p2 = (select_ln132_fu_240_p3 + 13'd1);

assign add_ln136_fu_276_p2 = (n_cast_fu_272_p1 + zext_ln132_fu_262_p1);

assign and_ln140_1_fu_440_p2 = (grp_fu_509_p_dout0 & and_ln140_fu_434_p2);

assign and_ln140_fu_434_p2 = (or_ln140_fu_410_p2 & or_ln140_1_fu_428_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage4_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage4_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign b_q_fu_318_p1 = xor_ln14_fu_312_p2;

assign bitcast_ln140_1_fu_381_p1 = max_corr_val_1_reg_673;

assign bitcast_ln140_fu_364_p1 = corr_abs_reg_666;

assign bitcast_ln14_fu_309_p1 = a_q_2_reg_572;

assign g_baseband_data_i_address0 = zext_ln136_fu_282_p1;

assign g_baseband_data_q_address0 = zext_ln136_fu_282_p1;

assign g_matched_filter_template_i_address0 = n_cast11_fu_266_p1;

assign g_matched_filter_template_q_address0 = n_cast11_fu_266_p1;

assign grp_fu_509_p_ce = 1'b1;

assign grp_fu_509_p_din0 = corr_abs_reg_666;

assign grp_fu_509_p_din1 = max_corr_val_fu_78;

assign grp_fu_509_p_opcode = 5'd2;

assign grp_fu_806_p_ce = 1'b1;

assign grp_fu_806_p_din0 = grp_fu_157_p0;

assign grp_fu_806_p_din1 = grp_fu_157_p1;

assign grp_fu_814_p_ce = 1'b1;

assign grp_fu_814_p_din0 = grp_fu_149_p0;

assign grp_fu_814_p_din1 = grp_fu_149_p1;

assign grp_fu_814_p_opcode = grp_fu_149_opcode;

assign grp_fu_818_p_ce = 1'b1;

assign grp_fu_818_p_din0 = grp_fu_153_p0;

assign grp_fu_818_p_din1 = grp_fu_153_p1;

assign grp_fu_818_p_opcode = 2'd0;

assign grp_fu_826_p_ce = 1'b1;

assign grp_fu_826_p_din0 = a_q_3_reg_583;

assign grp_fu_826_p_din1 = grp_fu_161_p1;

assign grp_fu_830_p_ce = 1'b1;

assign grp_fu_830_p_din0 = 32'd0;

assign grp_fu_830_p_din1 = add_i2_dup_reg_661;

assign icmp_ln132_fu_219_p2 = ((indvar_flatten_fu_86 == 25'd16793600) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_234_p2 = ((n_fu_70 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln140_1_fu_404_p2 = ((trunc_ln140_fu_377_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_2_fu_416_p2 = ((tmp_14_dup_fu_384_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln140_3_fu_422_p2 = ((trunc_ln140_1_fu_394_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_398_p2 = ((tmp_13_dup_fu_367_p4 != 8'd255) ? 1'b1 : 1'b0);

assign n_cast11_fu_266_p1 = select_ln132_fu_240_p3;

assign n_cast_fu_272_p1 = select_ln132_fu_240_p3;

assign or_ln140_1_fu_428_p2 = (icmp_ln140_3_fu_422_p2 | icmp_ln140_2_fu_416_p2);

assign or_ln140_fu_410_p2 = (icmp_ln140_fu_398_p2 | icmp_ln140_1_fu_404_p2);

assign peak_idx_2_out = peak_idx_5_fu_449_p3;

assign peak_idx_5_fu_449_p3 = ((and_ln140_1_fu_440_p2[0:0] == 1'b1) ? zext_ln140_fu_446_p1 : peak_idx_fu_74);

assign select_ln132_1_fu_328_p3 = ((icmp_ln134_reg_544_pp0_iter2_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_dot_prod_i_1);

assign select_ln132_2_fu_339_p3 = ((icmp_ln134_reg_544_pp0_iter2_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_dot_prod_q_1);

assign select_ln132_3_fu_254_p3 = ((icmp_ln134_fu_234_p2[0:0] == 1'b1) ? add_ln132_1_fu_248_p2 : peak_idx_1_fu_82);

assign select_ln132_4_fu_464_p3 = ((icmp_ln134_reg_544_pp0_iter7_reg[0:0] == 1'b1) ? select_ln140_fu_458_p3 : max_corr_val_1_reg_673);

assign select_ln132_5_fu_470_p3 = ((icmp_ln134_reg_544_pp0_iter7_reg[0:0] == 1'b1) ? peak_idx_5_fu_449_p3 : peak_idx_fu_74);

assign select_ln132_fu_240_p3 = ((icmp_ln134_fu_234_p2[0:0] == 1'b1) ? 13'd0 : n_fu_70);

assign select_ln140_fu_458_p3 = ((and_ln140_1_fu_440_p2[0:0] == 1'b1) ? corr_abs_reg_666 : max_corr_val_1_reg_673);

assign tmp_13_dup_fu_367_p4 = {{bitcast_ln140_fu_364_p1[30:23]}};

assign tmp_14_dup_fu_384_p4 = {{bitcast_ln140_1_fu_381_p1[30:23]}};

assign trunc_ln140_1_fu_394_p1 = bitcast_ln140_1_fu_381_p1[22:0];

assign trunc_ln140_fu_377_p1 = bitcast_ln140_fu_364_p1[22:0];

assign xor_ln14_fu_312_p2 = (bitcast_ln14_fu_309_p1 ^ 32'd2147483648);

assign zext_ln132_fu_262_p1 = select_ln132_3_fu_254_p3;

assign zext_ln136_fu_282_p1 = add_ln136_fu_276_p2;

assign zext_ln140_fu_446_p1 = lag_reg_535_pp0_iter7_reg;

endmodule //qpsk_hls_top_qpsk_hls_top_Pipeline_XCORR_LOOP_DOT_PROD_LOOP
