// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_qpsk_hls_top_Pipeline_FIND_MAX_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mean_i,
        mean_q,
        max_abs_val_V_out,
        max_abs_val_V_out_ap_vld,
        g_rx_samples_int_i_V_address0,
        g_rx_samples_int_i_V_ce0,
        g_rx_samples_int_i_V_we0,
        g_rx_samples_int_i_V_d0,
        g_rx_samples_int_i_V_address1,
        g_rx_samples_int_i_V_ce1,
        g_rx_samples_int_i_V_q1,
        g_rx_samples_int_q_V_address0,
        g_rx_samples_int_q_V_ce0,
        g_rx_samples_int_q_V_we0,
        g_rx_samples_int_q_V_d0,
        g_rx_samples_int_q_V_address1,
        g_rx_samples_int_q_V_ce1,
        g_rx_samples_int_q_V_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] mean_i;
input  [15:0] mean_q;
output  [15:0] max_abs_val_V_out;
output   max_abs_val_V_out_ap_vld;
output  [13:0] g_rx_samples_int_i_V_address0;
output   g_rx_samples_int_i_V_ce0;
output   g_rx_samples_int_i_V_we0;
output  [15:0] g_rx_samples_int_i_V_d0;
output  [13:0] g_rx_samples_int_i_V_address1;
output   g_rx_samples_int_i_V_ce1;
input  [15:0] g_rx_samples_int_i_V_q1;
output  [13:0] g_rx_samples_int_q_V_address0;
output   g_rx_samples_int_q_V_ce0;
output   g_rx_samples_int_q_V_we0;
output  [15:0] g_rx_samples_int_q_V_d0;
output  [13:0] g_rx_samples_int_q_V_address1;
output   g_rx_samples_int_q_V_ce1;
input  [15:0] g_rx_samples_int_q_V_q1;

reg ap_idle;
reg max_abs_val_V_out_ap_vld;
reg g_rx_samples_int_i_V_ce0;
reg g_rx_samples_int_i_V_we0;
reg g_rx_samples_int_i_V_ce1;
reg g_rx_samples_int_q_V_ce0;
reg g_rx_samples_int_q_V_we0;
reg g_rx_samples_int_q_V_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln106_fu_126_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln106_reg_286;
reg   [13:0] g_rx_samples_int_i_V_addr_reg_290;
reg   [13:0] g_rx_samples_int_q_V_addr_reg_296;
wire   [15:0] abs_i_V_fu_185_p3;
reg   [15:0] abs_i_V_reg_302;
wire   [15:0] abs_q_V_fu_217_p3;
reg   [15:0] abs_q_V_reg_308;
wire   [63:0] zext_ln106_fu_138_p1;
wire    ap_block_pp0_stage0;
reg   [15:0] max_abs_val_V_fu_52;
wire   [15:0] max_abs_val_V_3_fu_245_p3;
wire    ap_loop_init;
reg   [13:0] i_2_fu_56;
wire   [13:0] add_ln106_fu_132_p2;
reg   [13:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] x_V_fu_149_p2;
wire   [15:0] x_V_1_fu_155_p2;
wire   [15:0] p_Val2_s_fu_161_p2;
wire   [0:0] p_Result_s_fu_177_p3;
wire   [15:0] p_Result_99_fu_167_p4;
wire   [15:0] p_Val2_134_fu_193_p2;
wire   [0:0] p_Result_98_fu_209_p3;
wire   [15:0] p_Result_100_fu_199_p4;
wire   [0:0] icmp_ln1080_fu_228_p2;
wire   [15:0] max_abs_val_V_1_fu_233_p3;
wire   [0:0] icmp_ln1080_1_fu_240_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

qpsk_hls_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln106_fu_126_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_2_fu_56 <= add_ln106_fu_132_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_56 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_abs_val_V_fu_52 <= 16'd1;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            max_abs_val_V_fu_52 <= max_abs_val_V_3_fu_245_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_i_V_reg_302 <= abs_i_V_fu_185_p3;
        abs_q_V_reg_308 <= abs_q_V_fu_217_p3;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln106_reg_286 <= icmp_ln106_fu_126_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln106_fu_126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_i_V_addr_reg_290 <= zext_ln106_fu_138_p1;
        g_rx_samples_int_q_V_addr_reg_296 <= zext_ln106_fu_138_p1;
    end
end

always @ (*) begin
    if (((icmp_ln106_fu_126_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 14'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_i_V_ce0 = 1'b1;
    end else begin
        g_rx_samples_int_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_i_V_ce1 = 1'b1;
    end else begin
        g_rx_samples_int_i_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_i_V_we0 = 1'b1;
    end else begin
        g_rx_samples_int_i_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_q_V_ce0 = 1'b1;
    end else begin
        g_rx_samples_int_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_q_V_ce1 = 1'b1;
    end else begin
        g_rx_samples_int_q_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_rx_samples_int_q_V_we0 = 1'b1;
    end else begin
        g_rx_samples_int_q_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_reg_286 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_abs_val_V_out_ap_vld = 1'b1;
    end else begin
        max_abs_val_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_i_V_fu_185_p3 = ((p_Result_s_fu_177_p3[0:0] == 1'b1) ? p_Result_99_fu_167_p4 : x_V_fu_149_p2);

assign abs_q_V_fu_217_p3 = ((p_Result_98_fu_209_p3[0:0] == 1'b1) ? p_Result_100_fu_199_p4 : x_V_1_fu_155_p2);

assign add_ln106_fu_132_p2 = (ap_sig_allocacmp_i + 14'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign g_rx_samples_int_i_V_address0 = g_rx_samples_int_i_V_addr_reg_290;

assign g_rx_samples_int_i_V_address1 = zext_ln106_fu_138_p1;

assign g_rx_samples_int_i_V_d0 = x_V_fu_149_p2;

assign g_rx_samples_int_q_V_address0 = g_rx_samples_int_q_V_addr_reg_296;

assign g_rx_samples_int_q_V_address1 = zext_ln106_fu_138_p1;

assign g_rx_samples_int_q_V_d0 = x_V_1_fu_155_p2;

assign icmp_ln106_fu_126_p2 = ((ap_sig_allocacmp_i == 14'd8196) ? 1'b1 : 1'b0);

assign icmp_ln1080_1_fu_240_p2 = (($signed(abs_q_V_reg_308) > $signed(max_abs_val_V_1_fu_233_p3)) ? 1'b1 : 1'b0);

assign icmp_ln1080_fu_228_p2 = (($signed(abs_i_V_reg_302) > $signed(max_abs_val_V_fu_52)) ? 1'b1 : 1'b0);

assign max_abs_val_V_1_fu_233_p3 = ((icmp_ln1080_fu_228_p2[0:0] == 1'b1) ? abs_i_V_reg_302 : max_abs_val_V_fu_52);

assign max_abs_val_V_3_fu_245_p3 = ((icmp_ln1080_1_fu_240_p2[0:0] == 1'b1) ? abs_q_V_reg_308 : max_abs_val_V_1_fu_233_p3);

assign max_abs_val_V_out = max_abs_val_V_fu_52;

assign p_Result_100_fu_199_p4 = {|(1'd0), p_Val2_134_fu_193_p2[15 - 1:0]};

assign p_Result_98_fu_209_p3 = x_V_1_fu_155_p2[32'd15];

assign p_Result_99_fu_167_p4 = {|(1'd0), p_Val2_s_fu_161_p2[15 - 1:0]};

assign p_Result_s_fu_177_p3 = x_V_fu_149_p2[32'd15];

assign p_Val2_134_fu_193_p2 = (16'd0 - x_V_1_fu_155_p2);

assign p_Val2_s_fu_161_p2 = (16'd0 - x_V_fu_149_p2);

assign x_V_1_fu_155_p2 = (g_rx_samples_int_q_V_q1 - mean_q);

assign x_V_fu_149_p2 = (g_rx_samples_int_i_V_q1 - mean_i);

assign zext_ln106_fu_138_p1 = ap_sig_allocacmp_i;

endmodule //qpsk_hls_top_qpsk_hls_top_Pipeline_FIND_MAX_LOOP
