// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_qpsk_hls_top_Pipeline_VITIS_LOOP_178_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln178,
        add_ln174_1,
        frame_data_i_V_address0,
        frame_data_i_V_ce0,
        frame_data_i_V_we0,
        frame_data_i_V_d0,
        frame_data_q_V_address0,
        frame_data_q_V_ce0,
        frame_data_q_V_we0,
        frame_data_q_V_d0,
        g_baseband_data_i_V_address0,
        g_baseband_data_i_V_ce0,
        g_baseband_data_i_V_q0,
        g_baseband_data_q_V_address0,
        g_baseband_data_q_V_ce0,
        g_baseband_data_q_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sext_ln178;
input  [13:0] add_ln174_1;
output  [11:0] frame_data_i_V_address0;
output   frame_data_i_V_ce0;
output   frame_data_i_V_we0;
output  [17:0] frame_data_i_V_d0;
output  [11:0] frame_data_q_V_address0;
output   frame_data_q_V_ce0;
output   frame_data_q_V_we0;
output  [17:0] frame_data_q_V_d0;
output  [13:0] g_baseband_data_i_V_address0;
output   g_baseband_data_i_V_ce0;
input  [17:0] g_baseband_data_i_V_q0;
output  [13:0] g_baseband_data_q_V_address0;
output   g_baseband_data_q_V_ce0;
input  [17:0] g_baseband_data_q_V_q0;

reg ap_idle;
reg frame_data_i_V_ce0;
reg frame_data_i_V_we0;
reg frame_data_q_V_ce0;
reg frame_data_q_V_we0;
reg g_baseband_data_i_V_ce0;
reg g_baseband_data_q_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln178_fu_128_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [12:0] i_reg_201;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln181_fu_178_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] i_6_cast217_fu_189_p1;
reg   [12:0] i_6_fu_46;
wire   [12:0] add_ln178_fu_134_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_i;
wire   [11:0] trunc_ln179_fu_144_p1;
wire   [32:0] i_6_cast_fu_140_p1;
wire  signed [32:0] sext_ln178_cast_fu_116_p1;
wire   [32:0] add_ln179_fu_152_p2;
wire   [13:0] zext_ln179_fu_148_p1;
wire   [0:0] icmp_ln180_fu_158_p2;
wire   [13:0] add_ln180_fu_164_p2;
wire   [13:0] idx_fu_170_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

qpsk_hls_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln178_fu_128_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_6_fu_46 <= add_ln178_fu_134_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_6_fu_46 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_201 <= ap_sig_allocacmp_i;
    end
end

always @ (*) begin
    if (((icmp_ln178_fu_128_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 13'd0;
    end else begin
        ap_sig_allocacmp_i = i_6_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        frame_data_i_V_ce0 = 1'b1;
    end else begin
        frame_data_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        frame_data_i_V_we0 = 1'b1;
    end else begin
        frame_data_i_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        frame_data_q_V_ce0 = 1'b1;
    end else begin
        frame_data_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        frame_data_q_V_we0 = 1'b1;
    end else begin
        frame_data_q_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_baseband_data_i_V_ce0 = 1'b1;
    end else begin
        g_baseband_data_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_baseband_data_q_V_ce0 = 1'b1;
    end else begin
        g_baseband_data_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln178_fu_134_p2 = (ap_sig_allocacmp_i + 13'd1);

assign add_ln179_fu_152_p2 = ($signed(i_6_cast_fu_140_p1) + $signed(sext_ln178_cast_fu_116_p1));

assign add_ln180_fu_164_p2 = (zext_ln179_fu_148_p1 + add_ln174_1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign frame_data_i_V_address0 = i_6_cast217_fu_189_p1;

assign frame_data_i_V_d0 = g_baseband_data_i_V_q0;

assign frame_data_q_V_address0 = i_6_cast217_fu_189_p1;

assign frame_data_q_V_d0 = g_baseband_data_q_V_q0;

assign g_baseband_data_i_V_address0 = zext_ln181_fu_178_p1;

assign g_baseband_data_q_V_address0 = zext_ln181_fu_178_p1;

assign i_6_cast217_fu_189_p1 = i_reg_201;

assign i_6_cast_fu_140_p1 = ap_sig_allocacmp_i;

assign icmp_ln178_fu_128_p2 = ((ap_sig_allocacmp_i == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_158_p2 = (($signed(add_ln179_fu_152_p2) > $signed(33'd8195)) ? 1'b1 : 1'b0);

assign idx_fu_170_p3 = ((icmp_ln180_fu_158_p2[0:0] == 1'b1) ? 14'd8195 : add_ln180_fu_164_p2);

assign sext_ln178_cast_fu_116_p1 = $signed(sext_ln178);

assign trunc_ln179_fu_144_p1 = ap_sig_allocacmp_i[11:0];

assign zext_ln179_fu_148_p1 = trunc_ln179_fu_144_p1;

assign zext_ln181_fu_178_p1 = idx_fu_170_p3;

endmodule //qpsk_hls_top_qpsk_hls_top_Pipeline_VITIS_LOOP_178_5
