// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_qpsk_hls_top_Pipeline_SAMPLE_VAR_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sampled_syms_i_V_address0,
        sampled_syms_i_V_ce0,
        sampled_syms_i_V_q0,
        mean_i_1,
        sampled_syms_q_V_address0,
        sampled_syms_q_V_ce0,
        sampled_syms_q_V_q0,
        mean_q_V,
        var_q_accum_V_2_out,
        var_q_accum_V_2_out_ap_vld,
        var_i_accum_V_2_out,
        var_i_accum_V_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] sampled_syms_i_V_address0;
output   sampled_syms_i_V_ce0;
input  [17:0] sampled_syms_i_V_q0;
input  [17:0] mean_i_1;
output  [5:0] sampled_syms_q_V_address0;
output   sampled_syms_q_V_ce0;
input  [17:0] sampled_syms_q_V_q0;
input  [17:0] mean_q_V;
output  [47:0] var_q_accum_V_2_out;
output   var_q_accum_V_2_out_ap_vld;
output  [47:0] var_i_accum_V_2_out;
output   var_i_accum_V_2_out_ap_vld;

reg ap_idle;
reg sampled_syms_i_V_ce0;
reg sampled_syms_q_V_ce0;
reg var_q_accum_V_2_out_ap_vld;
reg var_i_accum_V_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln209_fu_140_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln209_reg_324;
reg   [0:0] icmp_ln209_reg_324_pp0_iter1_reg;
wire  signed [17:0] diff_i_V_fu_163_p2;
reg  signed [17:0] diff_i_V_reg_338;
wire  signed [17:0] diff_q_V_fu_168_p2;
reg  signed [17:0] diff_q_V_reg_344;
wire   [51:0] r_V_29_fu_187_p2;
reg   [51:0] r_V_29_reg_350;
wire   [51:0] r_V_30_fu_207_p2;
reg   [51:0] r_V_30_reg_355;
wire   [63:0] zext_ln209_fu_152_p1;
wire    ap_block_pp0_stage0;
reg   [47:0] lhs_V_fu_58;
wire    ap_loop_init;
reg   [47:0] lhs_V_2_fu_62;
reg   [6:0] i_fu_66;
wire   [6:0] add_ln209_fu_146_p2;
reg   [6:0] ap_sig_allocacmp_i_8;
wire    ap_block_pp0_stage0_01001;
wire  signed [33:0] r_V_fu_173_p3;
wire  signed [33:0] r_V_27_fu_193_p3;
wire   [57:0] lhs_V_1_fu_219_p3;
wire  signed [57:0] sext_ln1245_fu_227_p1;
wire   [57:0] ret_V_fu_230_p2;
wire   [57:0] lhs_V_3_fu_246_p3;
wire  signed [57:0] sext_ln1245_1_fu_254_p1;
wire   [57:0] ret_V_6_fu_257_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

qpsk_hls_top_mul_34s_18s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 52 ))
mul_34s_18s_52_1_1_U74(
    .din0(r_V_fu_173_p3),
    .din1(diff_i_V_reg_338),
    .dout(r_V_29_fu_187_p2)
);

qpsk_hls_top_mul_34s_18s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 52 ))
mul_34s_18s_52_1_1_U75(
    .din0(r_V_27_fu_193_p3),
    .din1(diff_q_V_reg_344),
    .dout(r_V_30_fu_207_p2)
);

qpsk_hls_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln209_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln209_fu_146_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_V_2_fu_62 <= 48'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            lhs_V_2_fu_62 <= {{ret_V_6_fu_257_p2[57:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_V_fu_58 <= 48'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            lhs_V_fu_58 <= {{ret_V_fu_230_p2[57:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        diff_i_V_reg_338 <= diff_i_V_fu_163_p2;
        diff_q_V_reg_344 <= diff_q_V_fu_168_p2;
        icmp_ln209_reg_324 <= icmp_ln209_fu_140_p2;
        icmp_ln209_reg_324_pp0_iter1_reg <= icmp_ln209_reg_324;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        r_V_29_reg_350 <= r_V_29_fu_187_p2;
        r_V_30_reg_355 <= r_V_30_fu_207_p2;
    end
end

always @ (*) begin
    if (((icmp_ln209_fu_140_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_8 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_8 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sampled_syms_i_V_ce0 = 1'b1;
    end else begin
        sampled_syms_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sampled_syms_q_V_ce0 = 1'b1;
    end else begin
        sampled_syms_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln209_reg_324_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        var_i_accum_V_2_out_ap_vld = 1'b1;
    end else begin
        var_i_accum_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln209_reg_324_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        var_q_accum_V_2_out_ap_vld = 1'b1;
    end else begin
        var_q_accum_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln209_fu_146_p2 = (ap_sig_allocacmp_i_8 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign diff_i_V_fu_163_p2 = (sampled_syms_i_V_q0 - mean_i_1);

assign diff_q_V_fu_168_p2 = (sampled_syms_q_V_q0 - mean_q_V);

assign icmp_ln209_fu_140_p2 = ((ap_sig_allocacmp_i_8 == 7'd64) ? 1'b1 : 1'b0);

assign lhs_V_1_fu_219_p3 = {{lhs_V_fu_58}, {10'd0}};

assign lhs_V_3_fu_246_p3 = {{lhs_V_2_fu_62}, {10'd0}};

assign r_V_27_fu_193_p3 = {{diff_q_V_reg_344}, {16'd0}};

assign r_V_fu_173_p3 = {{diff_i_V_reg_338}, {16'd0}};

assign ret_V_6_fu_257_p2 = ($signed(lhs_V_3_fu_246_p3) + $signed(sext_ln1245_1_fu_254_p1));

assign ret_V_fu_230_p2 = ($signed(lhs_V_1_fu_219_p3) + $signed(sext_ln1245_fu_227_p1));

assign sampled_syms_i_V_address0 = zext_ln209_fu_152_p1;

assign sampled_syms_q_V_address0 = zext_ln209_fu_152_p1;

assign sext_ln1245_1_fu_254_p1 = $signed(r_V_30_reg_355);

assign sext_ln1245_fu_227_p1 = $signed(r_V_29_reg_350);

assign var_i_accum_V_2_out = lhs_V_fu_58;

assign var_q_accum_V_2_out = lhs_V_2_fu_62;

assign zext_ln209_fu_152_p1 = ap_sig_allocacmp_i_8;

endmodule //qpsk_hls_top_qpsk_hls_top_Pipeline_SAMPLE_VAR_LOOP
