// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_qpsk_hls_top_Pipeline_VITIS_LOOP_75_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        g_preamble_syms_ideal_i_V_address0,
        g_preamble_syms_ideal_i_V_ce0,
        g_preamble_syms_ideal_i_V_q0,
        g_preamble_syms_ideal_q_V_address0,
        g_preamble_syms_ideal_q_V_ce0,
        g_preamble_syms_ideal_q_V_q0,
        g_matched_filter_template_i_V_address0,
        g_matched_filter_template_i_V_ce0,
        g_matched_filter_template_i_V_we0,
        g_matched_filter_template_i_V_d0,
        g_matched_filter_template_i_V_address1,
        g_matched_filter_template_i_V_ce1,
        g_matched_filter_template_i_V_we1,
        g_matched_filter_template_i_V_d1,
        g_matched_filter_template_q_V_address0,
        g_matched_filter_template_q_V_ce0,
        g_matched_filter_template_q_V_we0,
        g_matched_filter_template_q_V_d0,
        g_matched_filter_template_q_V_address1,
        g_matched_filter_template_q_V_ce1,
        g_matched_filter_template_q_V_we1,
        g_matched_filter_template_q_V_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] g_preamble_syms_ideal_i_V_address0;
output   g_preamble_syms_ideal_i_V_ce0;
input  [17:0] g_preamble_syms_ideal_i_V_q0;
output  [5:0] g_preamble_syms_ideal_q_V_address0;
output   g_preamble_syms_ideal_q_V_ce0;
input  [17:0] g_preamble_syms_ideal_q_V_q0;
output  [11:0] g_matched_filter_template_i_V_address0;
output   g_matched_filter_template_i_V_ce0;
output   g_matched_filter_template_i_V_we0;
output  [17:0] g_matched_filter_template_i_V_d0;
output  [11:0] g_matched_filter_template_i_V_address1;
output   g_matched_filter_template_i_V_ce1;
output   g_matched_filter_template_i_V_we1;
output  [17:0] g_matched_filter_template_i_V_d1;
output  [11:0] g_matched_filter_template_q_V_address0;
output   g_matched_filter_template_q_V_ce0;
output   g_matched_filter_template_q_V_we0;
output  [17:0] g_matched_filter_template_q_V_d0;
output  [11:0] g_matched_filter_template_q_V_address1;
output   g_matched_filter_template_q_V_ce1;
output   g_matched_filter_template_q_V_we1;
output  [17:0] g_matched_filter_template_q_V_d1;

reg ap_idle;
reg g_preamble_syms_ideal_i_V_ce0;
reg g_preamble_syms_ideal_q_V_ce0;
reg[11:0] g_matched_filter_template_i_V_address0;
reg g_matched_filter_template_i_V_ce0;
reg g_matched_filter_template_i_V_we0;
reg[17:0] g_matched_filter_template_i_V_d0;
reg[11:0] g_matched_filter_template_i_V_address1;
reg g_matched_filter_template_i_V_ce1;
reg g_matched_filter_template_i_V_we1;
reg[17:0] g_matched_filter_template_i_V_d1;
reg[11:0] g_matched_filter_template_q_V_address0;
reg g_matched_filter_template_q_V_ce0;
reg g_matched_filter_template_q_V_we0;
reg[17:0] g_matched_filter_template_q_V_d0;
reg[11:0] g_matched_filter_template_q_V_address1;
reg g_matched_filter_template_q_V_ce1;
reg g_matched_filter_template_q_V_we1;
reg[17:0] g_matched_filter_template_q_V_d1;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln75_fu_247_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] icmp_ln75_reg_395;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] empty_99_fu_279_p1;
reg   [8:0] empty_99_reg_409;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
reg   [17:0] g_preamble_syms_ideal_i_V_load_reg_415;
reg   [17:0] g_preamble_syms_ideal_q_V_load_reg_421;
wire   [8:0] or_ln77_fu_283_p2;
reg   [8:0] or_ln77_reg_427;
wire   [8:0] or_ln77_1_fu_321_p2;
reg   [8:0] or_ln77_1_reg_432;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
wire   [9:0] zext_ln77_4_fu_332_p1;
reg   [9:0] zext_ln77_4_reg_437;
wire    ap_block_pp0_stage3_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] sym_cast_fu_259_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] template_idx_cast212_fu_273_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln77_fu_289_p1;
wire   [63:0] zext_ln77_2_fu_315_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln77_3_fu_326_p1;
wire   [63:0] zext_ln77_5_fu_341_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln77_6_fu_353_p1;
wire   [63:0] zext_ln77_7_fu_364_p1;
wire   [63:0] zext_ln77_8_fu_375_p1;
reg   [9:0] template_idx_fu_50;
wire   [9:0] add_ln75_1_fu_295_p2;
wire    ap_loop_init;
reg   [6:0] sym_fu_54;
wire   [6:0] add_ln75_fu_253_p2;
reg   [6:0] ap_sig_allocacmp_sym_1;
wire   [9:0] zext_ln77_1_fu_306_p1;
wire   [9:0] add_ln77_fu_309_p2;
wire   [9:0] add_ln77_1_fu_335_p2;
wire   [9:0] add_ln77_2_fu_347_p2;
wire   [9:0] add_ln77_3_fu_359_p2;
wire   [8:0] or_ln77_2_fu_370_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

qpsk_hls_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln75_fu_247_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            sym_fu_54 <= add_ln75_fu_253_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sym_fu_54 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        template_idx_fu_50 <= 10'd0;
    end else if (((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        template_idx_fu_50 <= add_ln75_1_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_99_reg_409 <= empty_99_fu_279_p1;
        g_preamble_syms_ideal_i_V_load_reg_415 <= g_preamble_syms_ideal_i_V_q0;
        g_preamble_syms_ideal_q_V_load_reg_421 <= g_preamble_syms_ideal_q_V_q0;
        or_ln77_reg_427[8 : 1] <= or_ln77_fu_283_p2[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln75_reg_395 <= icmp_ln75_fu_247_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln77_1_reg_432[8 : 2] <= or_ln77_1_fu_321_p2[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        zext_ln77_4_reg_437[8 : 2] <= zext_ln77_4_fu_332_p1[8 : 2];
    end
end

always @ (*) begin
    if (((icmp_ln75_fu_247_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sym_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_sym_1 = sym_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_matched_filter_template_i_V_address0 = zext_ln77_8_fu_375_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        g_matched_filter_template_i_V_address0 = zext_ln77_6_fu_353_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        g_matched_filter_template_i_V_address0 = zext_ln77_3_fu_326_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_i_V_address0 = zext_ln77_fu_289_p1;
    end else begin
        g_matched_filter_template_i_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_matched_filter_template_i_V_address1 = zext_ln77_7_fu_364_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        g_matched_filter_template_i_V_address1 = zext_ln77_5_fu_341_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        g_matched_filter_template_i_V_address1 = zext_ln77_2_fu_315_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_i_V_address1 = template_idx_cast212_fu_273_p1;
    end else begin
        g_matched_filter_template_i_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_i_V_ce0 = 1'b1;
    end else begin
        g_matched_filter_template_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_i_V_ce1 = 1'b1;
    end else begin
        g_matched_filter_template_i_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        g_matched_filter_template_i_V_d0 = g_preamble_syms_ideal_i_V_load_reg_415;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_i_V_d0 = g_preamble_syms_ideal_i_V_q0;
    end else begin
        g_matched_filter_template_i_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        g_matched_filter_template_i_V_d1 = g_preamble_syms_ideal_i_V_load_reg_415;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_i_V_d1 = g_preamble_syms_ideal_i_V_q0;
    end else begin
        g_matched_filter_template_i_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_i_V_we0 = 1'b1;
    end else begin
        g_matched_filter_template_i_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_i_V_we1 = 1'b1;
    end else begin
        g_matched_filter_template_i_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_matched_filter_template_q_V_address0 = zext_ln77_8_fu_375_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        g_matched_filter_template_q_V_address0 = zext_ln77_6_fu_353_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        g_matched_filter_template_q_V_address0 = zext_ln77_3_fu_326_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_q_V_address0 = zext_ln77_fu_289_p1;
    end else begin
        g_matched_filter_template_q_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_matched_filter_template_q_V_address1 = zext_ln77_7_fu_364_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        g_matched_filter_template_q_V_address1 = zext_ln77_5_fu_341_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        g_matched_filter_template_q_V_address1 = zext_ln77_2_fu_315_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_q_V_address1 = template_idx_cast212_fu_273_p1;
    end else begin
        g_matched_filter_template_q_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_q_V_ce0 = 1'b1;
    end else begin
        g_matched_filter_template_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_q_V_ce1 = 1'b1;
    end else begin
        g_matched_filter_template_q_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        g_matched_filter_template_q_V_d0 = g_preamble_syms_ideal_q_V_load_reg_421;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_q_V_d0 = g_preamble_syms_ideal_q_V_q0;
    end else begin
        g_matched_filter_template_q_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        g_matched_filter_template_q_V_d1 = g_preamble_syms_ideal_q_V_load_reg_421;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_matched_filter_template_q_V_d1 = g_preamble_syms_ideal_q_V_q0;
    end else begin
        g_matched_filter_template_q_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_q_V_we0 = 1'b1;
    end else begin
        g_matched_filter_template_q_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln75_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        g_matched_filter_template_q_V_we1 = 1'b1;
    end else begin
        g_matched_filter_template_q_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_preamble_syms_ideal_i_V_ce0 = 1'b1;
    end else begin
        g_preamble_syms_ideal_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_preamble_syms_ideal_q_V_ce0 = 1'b1;
    end else begin
        g_preamble_syms_ideal_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln75_1_fu_295_p2 = (template_idx_fu_50 + 10'd8);

assign add_ln75_fu_253_p2 = (ap_sig_allocacmp_sym_1 + 7'd1);

assign add_ln77_1_fu_335_p2 = (zext_ln77_4_fu_332_p1 + 10'd1);

assign add_ln77_2_fu_347_p2 = (zext_ln77_4_fu_332_p1 + 10'd2);

assign add_ln77_3_fu_359_p2 = (zext_ln77_4_reg_437 + 10'd3);

assign add_ln77_fu_309_p2 = (zext_ln77_1_fu_306_p1 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_99_fu_279_p1 = template_idx_fu_50[8:0];

assign g_preamble_syms_ideal_i_V_address0 = sym_cast_fu_259_p1;

assign g_preamble_syms_ideal_q_V_address0 = sym_cast_fu_259_p1;

assign icmp_ln75_fu_247_p2 = ((ap_sig_allocacmp_sym_1 == 7'd64) ? 1'b1 : 1'b0);

assign or_ln77_1_fu_321_p2 = (empty_99_reg_409 | 9'd3);

assign or_ln77_2_fu_370_p2 = (empty_99_reg_409 | 9'd7);

assign or_ln77_fu_283_p2 = (empty_99_fu_279_p1 | 9'd1);

assign sym_cast_fu_259_p1 = ap_sig_allocacmp_sym_1;

assign template_idx_cast212_fu_273_p1 = template_idx_fu_50;

assign zext_ln77_1_fu_306_p1 = or_ln77_reg_427;

assign zext_ln77_2_fu_315_p1 = add_ln77_fu_309_p2;

assign zext_ln77_3_fu_326_p1 = or_ln77_1_fu_321_p2;

assign zext_ln77_4_fu_332_p1 = or_ln77_1_reg_432;

assign zext_ln77_5_fu_341_p1 = add_ln77_1_fu_335_p2;

assign zext_ln77_6_fu_353_p1 = add_ln77_2_fu_347_p2;

assign zext_ln77_7_fu_364_p1 = add_ln77_3_fu_359_p2;

assign zext_ln77_8_fu_375_p1 = or_ln77_2_fu_370_p2;

assign zext_ln77_fu_289_p1 = or_ln77_fu_283_p2;

always @ (posedge ap_clk) begin
    or_ln77_reg_427[0] <= 1'b1;
    or_ln77_1_reg_432[1:0] <= 2'b11;
    zext_ln77_4_reg_437[1:0] <= 2'b11;
    zext_ln77_4_reg_437[9] <= 1'b0;
end

endmodule //qpsk_hls_top_qpsk_hls_top_Pipeline_VITIS_LOOP_75_2
