// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_qpsk_hls_top_Pipeline_VITIS_LOOP_237_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rx_preamble_syms_i_V_address0,
        rx_preamble_syms_i_V_ce0,
        rx_preamble_syms_i_V_q0,
        rx_preamble_syms_q_V_address0,
        rx_preamble_syms_q_V_ce0,
        rx_preamble_syms_q_V_q0,
        phase_sum_i_out,
        phase_sum_i_out_ap_vld,
        phase_sum_q_out,
        phase_sum_q_out_ap_vld,
        g_preamble_syms_ideal_i_V_address0,
        g_preamble_syms_ideal_i_V_ce0,
        g_preamble_syms_ideal_i_V_q0,
        g_preamble_syms_ideal_q_V_address0,
        g_preamble_syms_ideal_q_V_ce0,
        g_preamble_syms_ideal_q_V_q0,
        grp_fu_3094_p_din0,
        grp_fu_3094_p_din1,
        grp_fu_3094_p_opcode,
        grp_fu_3094_p_dout0,
        grp_fu_3094_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] rx_preamble_syms_i_V_address0;
output   rx_preamble_syms_i_V_ce0;
input  [17:0] rx_preamble_syms_i_V_q0;
output  [5:0] rx_preamble_syms_q_V_address0;
output   rx_preamble_syms_q_V_ce0;
input  [17:0] rx_preamble_syms_q_V_q0;
output  [31:0] phase_sum_i_out;
output   phase_sum_i_out_ap_vld;
output  [31:0] phase_sum_q_out;
output   phase_sum_q_out_ap_vld;
output  [5:0] g_preamble_syms_ideal_i_V_address0;
output   g_preamble_syms_ideal_i_V_ce0;
input  [17:0] g_preamble_syms_ideal_i_V_q0;
output  [5:0] g_preamble_syms_ideal_q_V_address0;
output   g_preamble_syms_ideal_q_V_ce0;
input  [17:0] g_preamble_syms_ideal_q_V_q0;
output  [31:0] grp_fu_3094_p_din0;
output  [31:0] grp_fu_3094_p_din1;
output  [1:0] grp_fu_3094_p_opcode;
input  [31:0] grp_fu_3094_p_dout0;
output   grp_fu_3094_p_ce;

reg ap_idle;
reg rx_preamble_syms_i_V_ce0;
reg rx_preamble_syms_q_V_ce0;
reg phase_sum_i_out_ap_vld;
reg phase_sum_q_out_ap_vld;
reg g_preamble_syms_ideal_i_V_ce0;
reg g_preamble_syms_ideal_q_V_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state10_pp0_stage4_iter1;
wire    ap_block_state15_pp0_stage4_iter2;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln237_reg_973;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_192;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state12_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state14_pp0_stage3_iter2;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln237_fu_214_p2;
reg   [0:0] icmp_ln237_reg_973_pp0_iter1_reg;
reg   [17:0] a_i_V_reg_997;
reg   [17:0] a_q_V_1_reg_1002;
reg   [17:0] a_i_V_1_reg_1007;
reg   [17:0] a_q_V_reg_1012;
wire   [17:0] b_q_V_fu_239_p2;
reg   [17:0] b_q_V_reg_1017;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state13_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_11001;
wire  signed [65:0] sext_ln1168_fu_258_p1;
reg  signed [65:0] sext_ln1168_reg_1022;
wire  signed [65:0] sext_ln1171_fu_262_p1;
reg  signed [65:0] sext_ln1171_reg_1027;
wire   [65:0] r_V_21_fu_266_p2;
reg   [65:0] r_V_21_reg_1032;
wire  signed [65:0] sext_ln1168_5_fu_286_p1;
reg  signed [65:0] sext_ln1168_5_reg_1037;
wire  signed [65:0] sext_ln1171_4_fu_290_p1;
reg  signed [65:0] sext_ln1171_4_reg_1042;
wire   [65:0] r_V_23_fu_294_p2;
reg   [65:0] r_V_23_reg_1047;
wire   [65:0] r_V_24_fu_304_p2;
reg   [65:0] r_V_24_reg_1052;
wire    ap_block_pp0_stage4_11001;
wire   [17:0] result_i_V_fu_308_p4;
reg   [17:0] result_i_V_reg_1057;
reg   [0:0] p_Result_91_reg_1063;
wire   [17:0] tmp_V_fu_326_p2;
reg   [17:0] tmp_V_reg_1069;
wire   [65:0] r_V_25_fu_332_p2;
reg   [65:0] r_V_25_reg_1074;
wire   [0:0] icmp_ln988_fu_336_p2;
reg   [0:0] icmp_ln988_reg_1079;
wire   [17:0] tmp_V_9_fu_341_p3;
reg   [17:0] tmp_V_9_reg_1084;
wire   [0:0] icmp_ln1011_fu_476_p2;
reg   [0:0] icmp_ln1011_reg_1089;
wire   [31:0] add_ln1011_fu_482_p2;
reg   [31:0] add_ln1011_reg_1094;
wire   [31:0] sub_ln1012_fu_488_p2;
reg   [31:0] sub_ln1012_reg_1099;
wire   [0:0] and_ln1002_fu_494_p2;
reg   [0:0] and_ln1002_reg_1104;
wire   [7:0] trunc_ln996_fu_500_p1;
reg   [7:0] trunc_ln996_reg_1109;
wire   [17:0] result_q_V_fu_508_p4;
reg   [17:0] result_q_V_reg_1114;
wire   [31:0] select_ln988_fu_623_p3;
reg   [31:0] select_ln988_reg_1120;
reg   [0:0] p_Result_94_reg_1125;
wire   [17:0] tmp_V_7_fu_638_p2;
reg   [17:0] tmp_V_7_reg_1131;
wire   [0:0] icmp_ln988_1_fu_648_p2;
reg   [0:0] icmp_ln988_1_reg_1141;
wire   [17:0] tmp_V_10_fu_653_p3;
reg   [17:0] tmp_V_10_reg_1146;
wire   [0:0] icmp_ln1011_1_fu_788_p2;
reg   [0:0] icmp_ln1011_1_reg_1151;
wire   [31:0] add_ln1011_1_fu_794_p2;
reg   [31:0] add_ln1011_1_reg_1156;
wire   [31:0] sub_ln1012_1_fu_800_p2;
reg   [31:0] sub_ln1012_1_reg_1161;
wire   [0:0] and_ln1002_1_fu_806_p2;
reg   [0:0] and_ln1002_1_reg_1166;
wire   [7:0] trunc_ln996_2_fu_812_p1;
reg   [7:0] trunc_ln996_2_reg_1171;
wire   [31:0] select_ln988_1_fu_921_p3;
reg   [31:0] select_ln988_1_reg_1176;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] i_10_cast_fu_226_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] phase_sum_q_fu_110;
reg   [31:0] ap_sig_allocacmp_phase_sum_q_load;
wire    ap_block_pp0_stage4;
wire    ap_loop_init;
reg   [31:0] phase_sum_i_fu_114;
reg   [31:0] ap_sig_allocacmp_phase_sum_i_load;
wire    ap_block_pp0_stage2;
reg   [6:0] i_fu_118;
wire   [6:0] add_ln237_fu_220_p2;
reg   [6:0] ap_sig_allocacmp_i_6;
wire    ap_block_pp0_stage4_01001;
reg   [31:0] grp_fu_188_p0;
reg   [31:0] grp_fu_188_p1;
wire  signed [33:0] r_V_fu_244_p3;
wire  signed [33:0] shl_ln737_s_fu_251_p3;
wire    ap_block_pp0_stage3;
wire  signed [33:0] r_V_22_fu_272_p3;
wire  signed [33:0] shl_ln737_2_fu_279_p3;
wire  signed [33:0] r_V_24_fu_304_p0;
wire  signed [33:0] r_V_24_fu_304_p1;
wire   [65:0] ret_V_fu_300_p2;
wire  signed [33:0] r_V_25_fu_332_p0;
wire  signed [33:0] r_V_25_fu_332_p1;
reg   [17:0] p_Result_s_fu_346_p4;
wire   [31:0] p_Result_92_fu_356_p3;
reg   [31:0] l_fu_364_p3;
wire   [31:0] sub_ln997_fu_372_p2;
wire   [31:0] lsb_index_fu_382_p2;
wire   [30:0] tmp_fu_388_p4;
wire   [4:0] trunc_ln1000_fu_404_p1;
wire   [4:0] sub_ln1000_fu_408_p2;
wire   [17:0] zext_ln1000_fu_414_p1;
wire   [17:0] lshr_ln1000_fu_418_p2;
wire   [17:0] p_Result_80_fu_424_p2;
wire   [0:0] tmp_57_fu_436_p3;
wire   [0:0] icmp_ln999_fu_398_p2;
wire   [0:0] icmp_ln1000_fu_430_p2;
wire   [17:0] trunc_ln997_fu_378_p1;
wire   [17:0] add_ln1002_fu_456_p2;
wire   [0:0] p_Result_81_fu_462_p3;
wire   [0:0] and_ln999_fu_450_p2;
wire   [0:0] a_fu_470_p2;
wire   [0:0] xor_ln1002_fu_444_p2;
wire    ap_block_pp0_stage1;
wire   [65:0] ret_V_5_fu_504_p2;
wire   [63:0] zext_ln1010_fu_518_p1;
wire   [63:0] zext_ln1011_fu_521_p1;
wire   [63:0] zext_ln1012_fu_530_p1;
wire   [63:0] lshr_ln1011_fu_524_p2;
wire   [63:0] shl_ln1012_fu_533_p2;
wire   [63:0] m_12_fu_539_p3;
wire   [63:0] zext_ln1014_fu_546_p1;
wire   [63:0] m_15_fu_549_p2;
wire   [62:0] m_21_fu_555_p4;
wire   [0:0] p_Result_82_fu_569_p3;
wire   [7:0] sub_ln1017_fu_585_p2;
wire   [7:0] select_ln996_fu_577_p3;
wire   [7:0] add_ln1017_fu_590_p2;
wire   [63:0] zext_ln1015_fu_565_p1;
wire   [8:0] tmp_5_fu_596_p3;
wire   [63:0] p_Result_93_fu_603_p5;
wire   [31:0] LD_fu_615_p1;
wire   [31:0] bitcast_ln756_fu_619_p1;
reg   [17:0] p_Result_85_fu_658_p4;
wire   [31:0] p_Result_95_fu_668_p3;
reg   [31:0] l_1_fu_676_p3;
wire   [31:0] sub_ln997_1_fu_684_p2;
wire   [31:0] lsb_index_2_fu_694_p2;
wire   [30:0] tmp_60_fu_700_p4;
wire   [4:0] trunc_ln1000_2_fu_716_p1;
wire   [4:0] sub_ln1000_2_fu_720_p2;
wire   [17:0] zext_ln1000_2_fu_726_p1;
wire   [17:0] lshr_ln1000_2_fu_730_p2;
wire   [17:0] p_Result_87_fu_736_p2;
wire   [0:0] tmp_61_fu_748_p3;
wire   [0:0] icmp_ln999_2_fu_710_p2;
wire   [0:0] icmp_ln1000_1_fu_742_p2;
wire   [17:0] trunc_ln997_2_fu_690_p1;
wire   [17:0] add_ln1002_1_fu_768_p2;
wire   [0:0] p_Result_88_fu_774_p3;
wire   [0:0] and_ln999_1_fu_762_p2;
wire   [0:0] a_2_fu_782_p2;
wire   [0:0] xor_ln1002_2_fu_756_p2;
wire   [63:0] zext_ln1010_1_fu_816_p1;
wire   [63:0] zext_ln1011_1_fu_819_p1;
wire   [63:0] zext_ln1012_1_fu_828_p1;
wire   [63:0] lshr_ln1011_1_fu_822_p2;
wire   [63:0] shl_ln1012_1_fu_831_p2;
wire   [63:0] m_17_fu_837_p3;
wire   [63:0] zext_ln1014_1_fu_844_p1;
wire   [63:0] m_18_fu_847_p2;
wire   [62:0] m_fu_853_p4;
wire   [0:0] p_Result_89_fu_867_p3;
wire   [7:0] sub_ln1017_1_fu_883_p2;
wire   [7:0] select_ln996_2_fu_875_p3;
wire   [7:0] add_ln1017_1_fu_888_p2;
wire   [63:0] zext_ln1015_2_fu_863_p1;
wire   [8:0] tmp_6_fu_894_p3;
wire   [63:0] p_Result_96_fu_901_p5;
wire   [31:0] LD_2_fu_913_p1;
wire   [31:0] bitcast_ln756_1_fu_917_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage4_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

qpsk_hls_top_mul_34s_34s_66_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 66 ))
mul_34s_34s_66_1_1_U90(
    .din0(shl_ln737_s_fu_251_p3),
    .din1(r_V_fu_244_p3),
    .dout(r_V_21_fu_266_p2)
);

qpsk_hls_top_mul_34s_34s_66_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 66 ))
mul_34s_34s_66_1_1_U91(
    .din0(shl_ln737_2_fu_279_p3),
    .din1(r_V_22_fu_272_p3),
    .dout(r_V_23_fu_294_p2)
);

qpsk_hls_top_mul_34s_34s_66_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 66 ))
mul_34s_34s_66_1_1_U92(
    .din0(r_V_24_fu_304_p0),
    .din1(r_V_24_fu_304_p1),
    .dout(r_V_24_fu_304_p2)
);

qpsk_hls_top_mul_34s_34s_66_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 66 ))
mul_34s_34s_66_1_1_U93(
    .din0(r_V_25_fu_332_p0),
    .din1(r_V_25_fu_332_p1),
    .dout(r_V_25_fu_332_p2)
);

qpsk_hls_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln237_fu_214_p2 == 1'd0))) begin
            i_fu_118 <= add_ln237_fu_220_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_118 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phase_sum_i_fu_114 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        phase_sum_i_fu_114 <= reg_192;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phase_sum_q_fu_110 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        phase_sum_q_fu_110 <= reg_192;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_reg_973 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_i_V_1_reg_1007 <= g_preamble_syms_ideal_i_V_q0;
        a_i_V_reg_997 <= rx_preamble_syms_i_V_q0;
        a_q_V_1_reg_1002 <= rx_preamble_syms_q_V_q0;
        a_q_V_reg_1012 <= g_preamble_syms_ideal_q_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln1011_1_reg_1156 <= add_ln1011_1_fu_794_p2;
        and_ln1002_1_reg_1166 <= and_ln1002_1_fu_806_p2;
        icmp_ln1011_1_reg_1151 <= icmp_ln1011_1_fu_788_p2;
        icmp_ln988_1_reg_1141 <= icmp_ln988_1_fu_648_p2;
        sub_ln1012_1_reg_1161 <= sub_ln1012_1_fu_800_p2;
        tmp_V_10_reg_1146 <= tmp_V_10_fu_653_p3;
        trunc_ln996_2_reg_1171 <= trunc_ln996_2_fu_812_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln1011_reg_1094 <= add_ln1011_fu_482_p2;
        and_ln1002_reg_1104 <= and_ln1002_fu_494_p2;
        icmp_ln1011_reg_1089 <= icmp_ln1011_fu_476_p2;
        icmp_ln237_reg_973 <= icmp_ln237_fu_214_p2;
        icmp_ln237_reg_973_pp0_iter1_reg <= icmp_ln237_reg_973;
        icmp_ln988_reg_1079 <= icmp_ln988_fu_336_p2;
        r_V_25_reg_1074 <= r_V_25_fu_332_p2;
        sub_ln1012_reg_1099 <= sub_ln1012_fu_488_p2;
        tmp_V_9_reg_1084 <= tmp_V_9_fu_341_p3;
        trunc_ln996_reg_1109 <= trunc_ln996_fu_500_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_reg_973 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_q_V_reg_1017 <= b_q_V_fu_239_p2;
        r_V_21_reg_1032 <= r_V_21_fu_266_p2;
        sext_ln1168_reg_1022[65 : 16] <= sext_ln1168_fu_258_p1[65 : 16];
        sext_ln1171_reg_1027[65 : 16] <= sext_ln1171_fu_262_p1[65 : 16];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_reg_973 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        p_Result_91_reg_1063 <= ret_V_fu_300_p2[32'd65];
        r_V_24_reg_1052 <= r_V_24_fu_304_p2;
        result_i_V_reg_1057 <= {{ret_V_fu_300_p2[65:48]}};
        tmp_V_reg_1069 <= tmp_V_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_Result_94_reg_1125 <= ret_V_5_fu_504_p2[32'd65];
        result_q_V_reg_1114 <= {{ret_V_5_fu_504_p2[65:48]}};
        select_ln988_reg_1120 <= select_ln988_fu_623_p3;
        tmp_V_7_reg_1131 <= tmp_V_7_fu_638_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_reg_973 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        r_V_23_reg_1047 <= r_V_23_fu_294_p2;
        sext_ln1168_5_reg_1037[65 : 16] <= sext_ln1168_5_fu_286_p1[65 : 16];
        sext_ln1171_4_reg_1042[65 : 16] <= sext_ln1171_4_fu_290_p1[65 : 16];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_192 <= grp_fu_3094_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        select_ln988_1_reg_1176 <= select_ln988_1_fu_921_p3;
    end
end

always @ (*) begin
    if (((icmp_ln237_reg_973 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_6 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_6 = i_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_phase_sum_i_load = reg_192;
    end else begin
        ap_sig_allocacmp_phase_sum_i_load = phase_sum_i_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_sig_allocacmp_phase_sum_q_load = reg_192;
    end else begin
        ap_sig_allocacmp_phase_sum_q_load = phase_sum_q_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_preamble_syms_ideal_i_V_ce0 = 1'b1;
    end else begin
        g_preamble_syms_ideal_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g_preamble_syms_ideal_q_V_ce0 = 1'b1;
    end else begin
        g_preamble_syms_ideal_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_188_p0 = ap_sig_allocacmp_phase_sum_q_load;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_188_p0 = ap_sig_allocacmp_phase_sum_i_load;
        end else begin
            grp_fu_188_p0 = 'bx;
        end
    end else begin
        grp_fu_188_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_188_p1 = select_ln988_1_reg_1176;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_188_p1 = select_ln988_reg_1120;
        end else begin
            grp_fu_188_p1 = 'bx;
        end
    end else begin
        grp_fu_188_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln237_reg_973_pp0_iter1_reg == 1'd1))) begin
        phase_sum_i_out_ap_vld = 1'b1;
    end else begin
        phase_sum_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln237_reg_973_pp0_iter1_reg == 1'd1))) begin
        phase_sum_q_out_ap_vld = 1'b1;
    end else begin
        phase_sum_q_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_preamble_syms_i_V_ce0 = 1'b1;
    end else begin
        rx_preamble_syms_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_preamble_syms_q_V_ce0 = 1'b1;
    end else begin
        rx_preamble_syms_q_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_2_fu_913_p1 = p_Result_96_fu_901_p5[31:0];

assign LD_fu_615_p1 = p_Result_93_fu_603_p5[31:0];

assign a_2_fu_782_p2 = (p_Result_88_fu_774_p3 | and_ln999_1_fu_762_p2);

assign a_fu_470_p2 = (p_Result_81_fu_462_p3 | and_ln999_fu_450_p2);

assign add_ln1002_1_fu_768_p2 = ($signed(trunc_ln997_2_fu_690_p1) + $signed(18'd262120));

assign add_ln1002_fu_456_p2 = ($signed(trunc_ln997_fu_378_p1) + $signed(18'd262120));

assign add_ln1011_1_fu_794_p2 = ($signed(sub_ln997_1_fu_684_p2) + $signed(32'd4294967271));

assign add_ln1011_fu_482_p2 = ($signed(sub_ln997_fu_372_p2) + $signed(32'd4294967271));

assign add_ln1017_1_fu_888_p2 = (sub_ln1017_1_fu_883_p2 + select_ln996_2_fu_875_p3);

assign add_ln1017_fu_590_p2 = (sub_ln1017_fu_585_p2 + select_ln996_fu_577_p3);

assign add_ln237_fu_220_p2 = (ap_sig_allocacmp_i_6 + 7'd1);

assign and_ln1002_1_fu_806_p2 = (xor_ln1002_2_fu_756_p2 & a_2_fu_782_p2);

assign and_ln1002_fu_494_p2 = (xor_ln1002_fu_444_p2 & a_fu_470_p2);

assign and_ln999_1_fu_762_p2 = (icmp_ln999_2_fu_710_p2 & icmp_ln1000_1_fu_742_p2);

assign and_ln999_fu_450_p2 = (icmp_ln999_fu_398_p2 & icmp_ln1000_fu_430_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign b_q_V_fu_239_p2 = (18'd0 - a_q_V_reg_1012);

assign bitcast_ln756_1_fu_917_p1 = LD_2_fu_913_p1;

assign bitcast_ln756_fu_619_p1 = LD_fu_615_p1;

assign g_preamble_syms_ideal_i_V_address0 = i_10_cast_fu_226_p1;

assign g_preamble_syms_ideal_q_V_address0 = i_10_cast_fu_226_p1;

assign grp_fu_3094_p_ce = 1'b1;

assign grp_fu_3094_p_din0 = grp_fu_188_p0;

assign grp_fu_3094_p_din1 = grp_fu_188_p1;

assign grp_fu_3094_p_opcode = 2'd0;

assign i_10_cast_fu_226_p1 = ap_sig_allocacmp_i_6;

assign icmp_ln1000_1_fu_742_p2 = ((p_Result_87_fu_736_p2 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1000_fu_430_p2 = ((p_Result_80_fu_424_p2 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1011_1_fu_788_p2 = (($signed(lsb_index_2_fu_694_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1011_fu_476_p2 = (($signed(lsb_index_fu_382_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_214_p2 = ((ap_sig_allocacmp_i_6 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln988_1_fu_648_p2 = ((result_q_V_reg_1114 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln988_fu_336_p2 = ((result_i_V_reg_1057 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln999_2_fu_710_p2 = (($signed(tmp_60_fu_700_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln999_fu_398_p2 = (($signed(tmp_fu_388_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);


always @ (p_Result_95_fu_668_p3) begin
    if (p_Result_95_fu_668_p3[0] == 1'b1) begin
        l_1_fu_676_p3 = 32'd0;
    end else if (p_Result_95_fu_668_p3[1] == 1'b1) begin
        l_1_fu_676_p3 = 32'd1;
    end else if (p_Result_95_fu_668_p3[2] == 1'b1) begin
        l_1_fu_676_p3 = 32'd2;
    end else if (p_Result_95_fu_668_p3[3] == 1'b1) begin
        l_1_fu_676_p3 = 32'd3;
    end else if (p_Result_95_fu_668_p3[4] == 1'b1) begin
        l_1_fu_676_p3 = 32'd4;
    end else if (p_Result_95_fu_668_p3[5] == 1'b1) begin
        l_1_fu_676_p3 = 32'd5;
    end else if (p_Result_95_fu_668_p3[6] == 1'b1) begin
        l_1_fu_676_p3 = 32'd6;
    end else if (p_Result_95_fu_668_p3[7] == 1'b1) begin
        l_1_fu_676_p3 = 32'd7;
    end else if (p_Result_95_fu_668_p3[8] == 1'b1) begin
        l_1_fu_676_p3 = 32'd8;
    end else if (p_Result_95_fu_668_p3[9] == 1'b1) begin
        l_1_fu_676_p3 = 32'd9;
    end else if (p_Result_95_fu_668_p3[10] == 1'b1) begin
        l_1_fu_676_p3 = 32'd10;
    end else if (p_Result_95_fu_668_p3[11] == 1'b1) begin
        l_1_fu_676_p3 = 32'd11;
    end else if (p_Result_95_fu_668_p3[12] == 1'b1) begin
        l_1_fu_676_p3 = 32'd12;
    end else if (p_Result_95_fu_668_p3[13] == 1'b1) begin
        l_1_fu_676_p3 = 32'd13;
    end else if (p_Result_95_fu_668_p3[14] == 1'b1) begin
        l_1_fu_676_p3 = 32'd14;
    end else if (p_Result_95_fu_668_p3[15] == 1'b1) begin
        l_1_fu_676_p3 = 32'd15;
    end else if (p_Result_95_fu_668_p3[16] == 1'b1) begin
        l_1_fu_676_p3 = 32'd16;
    end else if (p_Result_95_fu_668_p3[17] == 1'b1) begin
        l_1_fu_676_p3 = 32'd17;
    end else if (p_Result_95_fu_668_p3[18] == 1'b1) begin
        l_1_fu_676_p3 = 32'd18;
    end else if (p_Result_95_fu_668_p3[19] == 1'b1) begin
        l_1_fu_676_p3 = 32'd19;
    end else if (p_Result_95_fu_668_p3[20] == 1'b1) begin
        l_1_fu_676_p3 = 32'd20;
    end else if (p_Result_95_fu_668_p3[21] == 1'b1) begin
        l_1_fu_676_p3 = 32'd21;
    end else if (p_Result_95_fu_668_p3[22] == 1'b1) begin
        l_1_fu_676_p3 = 32'd22;
    end else if (p_Result_95_fu_668_p3[23] == 1'b1) begin
        l_1_fu_676_p3 = 32'd23;
    end else if (p_Result_95_fu_668_p3[24] == 1'b1) begin
        l_1_fu_676_p3 = 32'd24;
    end else if (p_Result_95_fu_668_p3[25] == 1'b1) begin
        l_1_fu_676_p3 = 32'd25;
    end else if (p_Result_95_fu_668_p3[26] == 1'b1) begin
        l_1_fu_676_p3 = 32'd26;
    end else if (p_Result_95_fu_668_p3[27] == 1'b1) begin
        l_1_fu_676_p3 = 32'd27;
    end else if (p_Result_95_fu_668_p3[28] == 1'b1) begin
        l_1_fu_676_p3 = 32'd28;
    end else if (p_Result_95_fu_668_p3[29] == 1'b1) begin
        l_1_fu_676_p3 = 32'd29;
    end else if (p_Result_95_fu_668_p3[30] == 1'b1) begin
        l_1_fu_676_p3 = 32'd30;
    end else if (p_Result_95_fu_668_p3[31] == 1'b1) begin
        l_1_fu_676_p3 = 32'd31;
    end else begin
        l_1_fu_676_p3 = 32'd32;
    end
end


always @ (p_Result_92_fu_356_p3) begin
    if (p_Result_92_fu_356_p3[0] == 1'b1) begin
        l_fu_364_p3 = 32'd0;
    end else if (p_Result_92_fu_356_p3[1] == 1'b1) begin
        l_fu_364_p3 = 32'd1;
    end else if (p_Result_92_fu_356_p3[2] == 1'b1) begin
        l_fu_364_p3 = 32'd2;
    end else if (p_Result_92_fu_356_p3[3] == 1'b1) begin
        l_fu_364_p3 = 32'd3;
    end else if (p_Result_92_fu_356_p3[4] == 1'b1) begin
        l_fu_364_p3 = 32'd4;
    end else if (p_Result_92_fu_356_p3[5] == 1'b1) begin
        l_fu_364_p3 = 32'd5;
    end else if (p_Result_92_fu_356_p3[6] == 1'b1) begin
        l_fu_364_p3 = 32'd6;
    end else if (p_Result_92_fu_356_p3[7] == 1'b1) begin
        l_fu_364_p3 = 32'd7;
    end else if (p_Result_92_fu_356_p3[8] == 1'b1) begin
        l_fu_364_p3 = 32'd8;
    end else if (p_Result_92_fu_356_p3[9] == 1'b1) begin
        l_fu_364_p3 = 32'd9;
    end else if (p_Result_92_fu_356_p3[10] == 1'b1) begin
        l_fu_364_p3 = 32'd10;
    end else if (p_Result_92_fu_356_p3[11] == 1'b1) begin
        l_fu_364_p3 = 32'd11;
    end else if (p_Result_92_fu_356_p3[12] == 1'b1) begin
        l_fu_364_p3 = 32'd12;
    end else if (p_Result_92_fu_356_p3[13] == 1'b1) begin
        l_fu_364_p3 = 32'd13;
    end else if (p_Result_92_fu_356_p3[14] == 1'b1) begin
        l_fu_364_p3 = 32'd14;
    end else if (p_Result_92_fu_356_p3[15] == 1'b1) begin
        l_fu_364_p3 = 32'd15;
    end else if (p_Result_92_fu_356_p3[16] == 1'b1) begin
        l_fu_364_p3 = 32'd16;
    end else if (p_Result_92_fu_356_p3[17] == 1'b1) begin
        l_fu_364_p3 = 32'd17;
    end else if (p_Result_92_fu_356_p3[18] == 1'b1) begin
        l_fu_364_p3 = 32'd18;
    end else if (p_Result_92_fu_356_p3[19] == 1'b1) begin
        l_fu_364_p3 = 32'd19;
    end else if (p_Result_92_fu_356_p3[20] == 1'b1) begin
        l_fu_364_p3 = 32'd20;
    end else if (p_Result_92_fu_356_p3[21] == 1'b1) begin
        l_fu_364_p3 = 32'd21;
    end else if (p_Result_92_fu_356_p3[22] == 1'b1) begin
        l_fu_364_p3 = 32'd22;
    end else if (p_Result_92_fu_356_p3[23] == 1'b1) begin
        l_fu_364_p3 = 32'd23;
    end else if (p_Result_92_fu_356_p3[24] == 1'b1) begin
        l_fu_364_p3 = 32'd24;
    end else if (p_Result_92_fu_356_p3[25] == 1'b1) begin
        l_fu_364_p3 = 32'd25;
    end else if (p_Result_92_fu_356_p3[26] == 1'b1) begin
        l_fu_364_p3 = 32'd26;
    end else if (p_Result_92_fu_356_p3[27] == 1'b1) begin
        l_fu_364_p3 = 32'd27;
    end else if (p_Result_92_fu_356_p3[28] == 1'b1) begin
        l_fu_364_p3 = 32'd28;
    end else if (p_Result_92_fu_356_p3[29] == 1'b1) begin
        l_fu_364_p3 = 32'd29;
    end else if (p_Result_92_fu_356_p3[30] == 1'b1) begin
        l_fu_364_p3 = 32'd30;
    end else if (p_Result_92_fu_356_p3[31] == 1'b1) begin
        l_fu_364_p3 = 32'd31;
    end else begin
        l_fu_364_p3 = 32'd32;
    end
end

assign lsb_index_2_fu_694_p2 = ($signed(sub_ln997_1_fu_684_p2) + $signed(32'd4294967272));

assign lsb_index_fu_382_p2 = ($signed(sub_ln997_fu_372_p2) + $signed(32'd4294967272));

assign lshr_ln1000_2_fu_730_p2 = 18'd262143 >> zext_ln1000_2_fu_726_p1;

assign lshr_ln1000_fu_418_p2 = 18'd262143 >> zext_ln1000_fu_414_p1;

assign lshr_ln1011_1_fu_822_p2 = zext_ln1010_1_fu_816_p1 >> zext_ln1011_1_fu_819_p1;

assign lshr_ln1011_fu_524_p2 = zext_ln1010_fu_518_p1 >> zext_ln1011_fu_521_p1;

assign m_12_fu_539_p3 = ((icmp_ln1011_reg_1089[0:0] == 1'b1) ? lshr_ln1011_fu_524_p2 : shl_ln1012_fu_533_p2);

assign m_15_fu_549_p2 = (m_12_fu_539_p3 + zext_ln1014_fu_546_p1);

assign m_17_fu_837_p3 = ((icmp_ln1011_1_reg_1151[0:0] == 1'b1) ? lshr_ln1011_1_fu_822_p2 : shl_ln1012_1_fu_831_p2);

assign m_18_fu_847_p2 = (m_17_fu_837_p3 + zext_ln1014_1_fu_844_p1);

assign m_21_fu_555_p4 = {{m_15_fu_549_p2[63:1]}};

assign m_fu_853_p4 = {{m_18_fu_847_p2[63:1]}};

assign p_Result_80_fu_424_p2 = (tmp_V_9_fu_341_p3 & lshr_ln1000_fu_418_p2);

assign p_Result_81_fu_462_p3 = tmp_V_9_fu_341_p3[add_ln1002_fu_456_p2];

assign p_Result_82_fu_569_p3 = m_15_fu_549_p2[32'd25];

integer ap_tvar_int_0;

always @ (tmp_V_10_fu_653_p3) begin
    for (ap_tvar_int_0 = 18 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 17 - 0) begin
            p_Result_85_fu_658_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_85_fu_658_p4[ap_tvar_int_0] = tmp_V_10_fu_653_p3[17 - ap_tvar_int_0];
        end
    end
end

assign p_Result_87_fu_736_p2 = (tmp_V_10_fu_653_p3 & lshr_ln1000_2_fu_730_p2);

assign p_Result_88_fu_774_p3 = tmp_V_10_fu_653_p3[add_ln1002_1_fu_768_p2];

assign p_Result_89_fu_867_p3 = m_18_fu_847_p2[32'd25];

assign p_Result_92_fu_356_p3 = {{14'd16383}, {p_Result_s_fu_346_p4}};

assign p_Result_93_fu_603_p5 = {{zext_ln1015_fu_565_p1[63:32]}, {tmp_5_fu_596_p3}, {zext_ln1015_fu_565_p1[22:0]}};

assign p_Result_95_fu_668_p3 = {{14'd16383}, {p_Result_85_fu_658_p4}};

assign p_Result_96_fu_901_p5 = {{zext_ln1015_2_fu_863_p1[63:32]}, {tmp_6_fu_894_p3}, {zext_ln1015_2_fu_863_p1[22:0]}};

integer ap_tvar_int_1;

always @ (tmp_V_9_fu_341_p3) begin
    for (ap_tvar_int_1 = 18 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 17 - 0) begin
            p_Result_s_fu_346_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_346_p4[ap_tvar_int_1] = tmp_V_9_fu_341_p3[17 - ap_tvar_int_1];
        end
    end
end

assign phase_sum_i_out = phase_sum_i_fu_114;

assign phase_sum_q_out = phase_sum_q_fu_110;

assign r_V_22_fu_272_p3 = {{a_q_V_1_reg_1002}, {16'd0}};

assign r_V_24_fu_304_p0 = sext_ln1171_4_reg_1042;

assign r_V_24_fu_304_p1 = sext_ln1168_reg_1022;

assign r_V_25_fu_332_p0 = sext_ln1171_reg_1027;

assign r_V_25_fu_332_p1 = sext_ln1168_5_reg_1037;

assign r_V_fu_244_p3 = {{a_i_V_reg_997}, {16'd0}};

assign result_i_V_fu_308_p4 = {{ret_V_fu_300_p2[65:48]}};

assign result_q_V_fu_508_p4 = {{ret_V_5_fu_504_p2[65:48]}};

assign ret_V_5_fu_504_p2 = (r_V_24_reg_1052 + r_V_25_reg_1074);

assign ret_V_fu_300_p2 = (r_V_21_reg_1032 - r_V_23_reg_1047);

assign rx_preamble_syms_i_V_address0 = i_10_cast_fu_226_p1;

assign rx_preamble_syms_q_V_address0 = i_10_cast_fu_226_p1;

assign select_ln988_1_fu_921_p3 = ((icmp_ln988_1_reg_1141[0:0] == 1'b1) ? 32'd0 : bitcast_ln756_1_fu_917_p1);

assign select_ln988_fu_623_p3 = ((icmp_ln988_reg_1079[0:0] == 1'b1) ? 32'd0 : bitcast_ln756_fu_619_p1);

assign select_ln996_2_fu_875_p3 = ((p_Result_89_fu_867_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln996_fu_577_p3 = ((p_Result_82_fu_569_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign sext_ln1168_5_fu_286_p1 = r_V_22_fu_272_p3;

assign sext_ln1168_fu_258_p1 = r_V_fu_244_p3;

assign sext_ln1171_4_fu_290_p1 = shl_ln737_2_fu_279_p3;

assign sext_ln1171_fu_262_p1 = shl_ln737_s_fu_251_p3;

assign shl_ln1012_1_fu_831_p2 = zext_ln1010_1_fu_816_p1 << zext_ln1012_1_fu_828_p1;

assign shl_ln1012_fu_533_p2 = zext_ln1010_fu_518_p1 << zext_ln1012_fu_530_p1;

assign shl_ln737_2_fu_279_p3 = {{b_q_V_reg_1017}, {16'd0}};

assign shl_ln737_s_fu_251_p3 = {{a_i_V_1_reg_1007}, {16'd0}};

assign sub_ln1000_2_fu_720_p2 = (5'd11 - trunc_ln1000_2_fu_716_p1);

assign sub_ln1000_fu_408_p2 = (5'd11 - trunc_ln1000_fu_404_p1);

assign sub_ln1012_1_fu_800_p2 = (32'd25 - sub_ln997_1_fu_684_p2);

assign sub_ln1012_fu_488_p2 = (32'd25 - sub_ln997_fu_372_p2);

assign sub_ln1017_1_fu_883_p2 = (8'd2 - trunc_ln996_2_reg_1171);

assign sub_ln1017_fu_585_p2 = (8'd2 - trunc_ln996_reg_1109);

assign sub_ln997_1_fu_684_p2 = (32'd18 - l_1_fu_676_p3);

assign sub_ln997_fu_372_p2 = (32'd18 - l_fu_364_p3);

assign tmp_57_fu_436_p3 = lsb_index_fu_382_p2[32'd31];

assign tmp_5_fu_596_p3 = {{p_Result_91_reg_1063}, {add_ln1017_fu_590_p2}};

assign tmp_60_fu_700_p4 = {{lsb_index_2_fu_694_p2[31:1]}};

assign tmp_61_fu_748_p3 = lsb_index_2_fu_694_p2[32'd31];

assign tmp_6_fu_894_p3 = {{p_Result_94_reg_1125}, {add_ln1017_1_fu_888_p2}};

assign tmp_V_10_fu_653_p3 = ((p_Result_94_reg_1125[0:0] == 1'b1) ? tmp_V_7_reg_1131 : result_q_V_reg_1114);

assign tmp_V_7_fu_638_p2 = (18'd0 - result_q_V_fu_508_p4);

assign tmp_V_9_fu_341_p3 = ((p_Result_91_reg_1063[0:0] == 1'b1) ? tmp_V_reg_1069 : result_i_V_reg_1057);

assign tmp_V_fu_326_p2 = (18'd0 - result_i_V_fu_308_p4);

assign tmp_fu_388_p4 = {{lsb_index_fu_382_p2[31:1]}};

assign trunc_ln1000_2_fu_716_p1 = sub_ln997_1_fu_684_p2[4:0];

assign trunc_ln1000_fu_404_p1 = sub_ln997_fu_372_p2[4:0];

assign trunc_ln996_2_fu_812_p1 = l_1_fu_676_p3[7:0];

assign trunc_ln996_fu_500_p1 = l_fu_364_p3[7:0];

assign trunc_ln997_2_fu_690_p1 = sub_ln997_1_fu_684_p2[17:0];

assign trunc_ln997_fu_378_p1 = sub_ln997_fu_372_p2[17:0];

assign xor_ln1002_2_fu_756_p2 = (tmp_61_fu_748_p3 ^ 1'd1);

assign xor_ln1002_fu_444_p2 = (tmp_57_fu_436_p3 ^ 1'd1);

assign zext_ln1000_2_fu_726_p1 = sub_ln1000_2_fu_720_p2;

assign zext_ln1000_fu_414_p1 = sub_ln1000_fu_408_p2;

assign zext_ln1010_1_fu_816_p1 = tmp_V_10_reg_1146;

assign zext_ln1010_fu_518_p1 = tmp_V_9_reg_1084;

assign zext_ln1011_1_fu_819_p1 = add_ln1011_1_reg_1156;

assign zext_ln1011_fu_521_p1 = add_ln1011_reg_1094;

assign zext_ln1012_1_fu_828_p1 = sub_ln1012_1_reg_1161;

assign zext_ln1012_fu_530_p1 = sub_ln1012_reg_1099;

assign zext_ln1014_1_fu_844_p1 = and_ln1002_1_reg_1166;

assign zext_ln1014_fu_546_p1 = and_ln1002_reg_1104;

assign zext_ln1015_2_fu_863_p1 = m_fu_853_p4;

assign zext_ln1015_fu_565_p1 = m_21_fu_555_p4;

always @ (posedge ap_clk) begin
    sext_ln1168_reg_1022[15:0] <= 16'b0000000000000000;
    sext_ln1171_reg_1027[15:0] <= 16'b0000000000000000;
    sext_ln1168_5_reg_1037[15:0] <= 16'b0000000000000000;
    sext_ln1171_4_reg_1042[15:0] <= 16'b0000000000000000;
end

endmodule //qpsk_hls_top_qpsk_hls_top_Pipeline_VITIS_LOOP_237_8
