// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qpsk_hls_top_sqrt_fixed_18_2_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [17:0] x;
output  [16:0] ap_return;

reg   [17:0] x_read_reg_2637;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_11001;
reg   [17:0] x_read_reg_2637_pp0_iter1_reg;
reg   [17:0] x_read_reg_2637_pp0_iter2_reg;
reg   [17:0] x_read_reg_2637_pp0_iter3_reg;
reg   [17:0] x_read_reg_2637_pp0_iter4_reg;
reg   [17:0] x_read_reg_2637_pp0_iter5_reg;
reg   [17:0] x_read_reg_2637_pp0_iter6_reg;
reg   [17:0] x_read_reg_2637_pp0_iter7_reg;
reg   [17:0] x_read_reg_2637_pp0_iter8_reg;
reg   [17:0] x_read_reg_2637_pp0_iter9_reg;
wire   [0:0] res_I_V_fu_240_p2;
reg   [0:0] res_I_V_reg_2642;
reg   [0:0] res_I_V_reg_2642_pp0_iter1_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter2_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter3_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter4_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter5_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter6_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter7_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter8_reg;
reg   [0:0] res_I_V_reg_2642_pp0_iter9_reg;
wire   [0:0] res_I_V_2_fu_264_p2;
reg   [0:0] res_I_V_2_reg_2647;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter1_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter2_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter3_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter4_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter5_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter6_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter7_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter8_reg;
reg   [0:0] res_I_V_2_reg_2647_pp0_iter9_reg;
wire   [16:0] res_FH_V_33_fu_354_p3;
reg   [16:0] res_FH_V_33_reg_2667;
wire   [16:0] p_Val2_9_fu_362_p3;
reg   [16:0] p_Val2_9_reg_2673;
wire  signed [3:0] x_l_I_V_55_fu_370_p3;
reg  signed [3:0] x_l_I_V_55_reg_2678;
wire   [0:0] icmp_ln318_3_fu_404_p2;
reg   [0:0] icmp_ln318_3_reg_2683;
wire   [16:0] x_l_FH_V_27_fu_416_p2;
reg   [16:0] x_l_FH_V_27_reg_2688;
wire   [0:0] and_ln318_2_fu_428_p2;
reg   [0:0] and_ln318_2_reg_2693;
wire   [16:0] res_FH_V_35_fu_558_p3;
reg   [16:0] res_FH_V_35_reg_2700;
wire   [16:0] x_l_FH_V_30_fu_566_p3;
reg   [16:0] x_l_FH_V_30_reg_2706;
wire   [4:0] x_l_I_V_59_fu_574_p3;
reg   [4:0] x_l_I_V_59_reg_2711;
wire   [0:0] icmp_ln318_7_fu_609_p2;
reg   [0:0] icmp_ln318_7_reg_2717;
wire   [4:0] x_l_I_V_13_fu_621_p2;
reg   [4:0] x_l_I_V_13_reg_2722;
wire   [16:0] x_l_FH_V_31_fu_627_p2;
reg   [16:0] x_l_FH_V_31_reg_2727;
wire   [0:0] and_ln318_4_fu_639_p2;
reg   [0:0] and_ln318_4_reg_2732;
wire   [16:0] res_FH_V_37_fu_757_p3;
reg   [16:0] res_FH_V_37_reg_2739;
wire   [16:0] x_l_FH_V_34_fu_765_p3;
reg   [16:0] x_l_FH_V_34_reg_2745;
wire   [4:0] x_l_I_V_63_fu_773_p3;
reg   [4:0] x_l_I_V_63_reg_2750;
wire   [0:0] icmp_ln318_19_fu_808_p2;
reg   [0:0] icmp_ln318_19_reg_2756;
wire   [4:0] x_l_I_V_19_fu_820_p2;
reg   [4:0] x_l_I_V_19_reg_2761;
wire   [16:0] x_l_FH_V_35_fu_826_p2;
reg   [16:0] x_l_FH_V_35_reg_2766;
wire   [0:0] and_ln318_6_fu_838_p2;
reg   [0:0] and_ln318_6_reg_2771;
wire   [16:0] res_FH_V_39_fu_956_p3;
reg   [16:0] res_FH_V_39_reg_2778;
wire   [16:0] x_l_FH_V_38_fu_964_p3;
reg   [16:0] x_l_FH_V_38_reg_2784;
wire   [4:0] x_l_I_V_67_fu_972_p3;
reg   [4:0] x_l_I_V_67_reg_2789;
wire   [0:0] icmp_ln318_23_fu_1007_p2;
reg   [0:0] icmp_ln318_23_reg_2795;
wire   [4:0] x_l_I_V_25_fu_1019_p2;
reg   [4:0] x_l_I_V_25_reg_2800;
wire   [16:0] x_l_FH_V_39_fu_1025_p2;
reg   [16:0] x_l_FH_V_39_reg_2805;
wire   [0:0] and_ln318_8_fu_1037_p2;
reg   [0:0] and_ln318_8_reg_2810;
wire   [16:0] res_FH_V_40_fu_1171_p3;
reg   [16:0] res_FH_V_40_reg_2817;
wire   [16:0] x_l_FL_V_15_fu_1179_p3;
reg   [16:0] x_l_FL_V_15_reg_2823;
wire   [16:0] x_l_FH_V_42_fu_1187_p3;
reg   [16:0] x_l_FH_V_42_reg_2828;
wire   [4:0] x_l_I_V_71_fu_1195_p3;
reg   [4:0] x_l_I_V_71_reg_2835;
wire   [16:0] mul_FH_V_8_fu_1223_p4;
reg   [16:0] mul_FH_V_8_reg_2842;
wire   [0:0] icmp_ln318_8_fu_1240_p2;
reg   [0:0] icmp_ln318_8_reg_2848;
wire   [0:0] delta_V_fu_1246_p2;
reg   [0:0] delta_V_reg_2853;
wire   [16:0] p_neg169_fu_1258_p3;
reg   [16:0] p_neg169_reg_2858;
wire   [16:0] x_l_FL_V_fu_1266_p2;
reg   [16:0] x_l_FL_V_reg_2863;
wire   [0:0] and_ln318_10_fu_1296_p2;
reg   [0:0] and_ln318_10_reg_2868;
wire   [16:0] res_FH_V_41_fu_1358_p3;
reg   [16:0] res_FH_V_41_reg_2876;
wire   [16:0] x_l_FL_V_16_fu_1364_p3;
reg   [16:0] x_l_FL_V_16_reg_2882;
wire   [16:0] x_l_FH_V_44_fu_1369_p3;
reg   [16:0] x_l_FH_V_44_reg_2887;
wire   [4:0] x_l_I_V_73_fu_1375_p3;
reg   [4:0] x_l_I_V_73_reg_2892;
wire   [0:0] icmp_ln318_9_fu_1418_p2;
reg   [0:0] icmp_ln318_9_reg_2899;
wire   [0:0] delta_V_1_fu_1424_p2;
reg   [0:0] delta_V_1_reg_2904;
wire   [0:0] icmp_ln1548_1_fu_1436_p2;
reg   [0:0] icmp_ln1548_1_reg_2909;
wire   [16:0] x_l_FH_V_45_fu_1456_p2;
reg   [16:0] x_l_FH_V_45_reg_2914;
wire   [16:0] x_l_FL_V_3_fu_1462_p2;
reg   [16:0] x_l_FL_V_3_reg_2919;
wire   [0:0] and_ln318_12_fu_1492_p2;
reg   [0:0] and_ln318_12_reg_2924;
wire   [16:0] x_l_FH_V_46_fu_1551_p3;
reg   [16:0] x_l_FH_V_46_reg_2932;
wire   [16:0] x_l_FH_V_47_fu_1675_p2;
reg   [16:0] x_l_FH_V_47_reg_2937;
wire   [0:0] and_ln318_14_fu_1721_p2;
reg   [0:0] and_ln318_14_reg_2942;
wire   [16:0] res_FH_V_43_fu_1727_p3;
reg   [16:0] res_FH_V_43_reg_2947;
wire   [16:0] x_l_FL_V_18_fu_1735_p3;
reg   [16:0] x_l_FL_V_18_reg_2953;
wire   [4:0] x_l_I_V_77_fu_1743_p3;
reg   [4:0] x_l_I_V_77_reg_2960;
reg   [7:0] tmp_6_reg_2968;
reg   [4:0] tmp_5_reg_2973;
wire   [16:0] res_FH_V_44_fu_1913_p3;
reg   [16:0] res_FH_V_44_reg_2978;
wire   [16:0] x_l_FL_V_19_fu_1920_p3;
reg   [16:0] x_l_FL_V_19_reg_2984;
wire   [16:0] x_l_FH_V_50_fu_1927_p3;
reg   [16:0] x_l_FH_V_50_reg_2990;
wire   [4:0] x_l_I_V_79_fu_1935_p3;
reg   [4:0] x_l_I_V_79_reg_2999;
reg   [3:0] tmp_10_reg_3007;
wire   [16:0] mul_FL_V_4_fu_1962_p3;
reg   [16:0] mul_FL_V_4_reg_3012;
wire   [0:0] delta_V_4_fu_1970_p2;
reg   [0:0] delta_V_4_reg_3017;
wire   [16:0] p_neg173_fu_1976_p3;
reg   [16:0] p_neg173_reg_3023;
wire   [16:0] res_FH_V_45_fu_2093_p3;
reg   [16:0] res_FH_V_45_reg_3028;
wire   [16:0] x_l_FL_V_20_fu_2100_p3;
reg   [16:0] x_l_FL_V_20_reg_3034;
wire   [16:0] x_l_FH_V_52_fu_2107_p3;
reg   [16:0] x_l_FH_V_52_reg_3039;
wire   [4:0] x_l_I_V_81_fu_2114_p3;
reg   [4:0] x_l_I_V_81_reg_3046;
wire   [16:0] mul_FH_V_13_fu_2141_p4;
reg   [16:0] mul_FH_V_13_reg_3053;
wire   [0:0] icmp_ln318_13_fu_2158_p2;
reg   [0:0] icmp_ln318_13_reg_3059;
wire   [0:0] delta_V_5_fu_2164_p2;
reg   [0:0] delta_V_5_reg_3064;
wire   [16:0] p_neg174_fu_2176_p3;
reg   [16:0] p_neg174_reg_3069;
wire   [16:0] x_l_FL_V_11_fu_2184_p2;
reg   [16:0] x_l_FL_V_11_reg_3074;
wire   [0:0] and_ln318_20_fu_2214_p2;
reg   [0:0] and_ln318_20_reg_3079;
wire   [16:0] res_FH_V_46_fu_2276_p3;
reg   [16:0] res_FH_V_46_reg_3087;
wire   [16:0] x_l_FL_V_21_fu_2282_p3;
reg   [16:0] x_l_FL_V_21_reg_3093;
wire   [16:0] x_l_FH_V_54_fu_2287_p3;
reg   [16:0] x_l_FH_V_54_reg_3099;
wire   [4:0] x_l_I_V_83_fu_2293_p3;
reg   [4:0] x_l_I_V_83_reg_3104;
wire   [16:0] mul_FL_V_6_fu_2328_p3;
reg   [16:0] mul_FL_V_6_reg_3111;
wire   [0:0] icmp_ln318_14_fu_2336_p2;
reg   [0:0] icmp_ln318_14_reg_3116;
wire   [0:0] delta_V_6_fu_2342_p2;
reg   [0:0] delta_V_6_reg_3121;
wire   [0:0] icmp_ln1548_6_fu_2354_p2;
reg   [0:0] icmp_ln1548_6_reg_3126;
wire   [16:0] x_l_FH_V_55_fu_2374_p2;
reg   [16:0] x_l_FH_V_55_reg_3131;
wire   [0:0] and_ln318_22_fu_2404_p2;
reg   [0:0] and_ln318_22_reg_3136;
wire    ap_block_pp0_stage0;
wire   [1:0] x_l_I_V_52_fu_214_p4;
wire   [15:0] trunc_ln740_fu_228_p1;
wire   [2:0] zext_ln235_fu_224_p1;
wire   [2:0] p_Result_30_fu_246_p2;
wire   [2:0] x_l_I_V_53_fu_252_p3;
wire   [2:0] trunc_ln1_fu_270_p3;
wire   [1:0] tmp_15_fu_284_p4;
wire   [0:0] icmp_ln318_fu_278_p2;
wire   [0:0] icmp_ln318_1_fu_294_p2;
wire   [3:0] zext_ln235_1_fu_260_p1;
wire   [3:0] x_l_I_V_fu_306_p2;
wire   [3:0] x_l_I_V_4_fu_312_p3;
wire   [3:0] zext_ln712_fu_320_p1;
wire   [16:0] x_l_FH_V_fu_232_p3;
wire   [0:0] icmp_ln1547_fu_336_p2;
wire   [0:0] or_ln318_fu_300_p2;
wire   [0:0] xor_ln1547_fu_342_p2;
wire   [0:0] and_ln318_1_fu_348_p2;
wire   [16:0] x_l_FH_V_26_fu_330_p2;
wire   [3:0] x_l_I_V_54_fu_324_p2;
wire   [1:0] p_Result_s_96_fu_378_p4;
wire   [16:0] mul_FH_V_fu_388_p4;
wire   [0:0] icmp_ln318_2_fu_398_p2;
wire   [0:0] or_ln318_1_fu_410_p2;
wire   [0:0] icmp_ln1547_1_fu_422_p2;
wire  signed [4:0] sext_ln235_fu_434_p1;
wire   [4:0] x_l_I_V_7_fu_437_p2;
wire   [16:0] p_Result_31_fu_450_p4;
wire   [4:0] x_l_I_V_56_fu_443_p3;
wire   [16:0] res_FH_V_34_fu_459_p3;
wire   [2:0] p_Result_4_fu_477_p4;
wire   [4:0] x_l_I_V_57_fu_470_p3;
wire   [16:0] x_l_FH_V_28_fu_465_p3;
wire   [16:0] mul_FH_V_1_fu_487_p5;
wire   [0:0] icmp_ln318_4_fu_498_p2;
wire   [0:0] icmp_ln318_5_fu_504_p2;
wire   [4:0] x_l_I_V_10_fu_516_p2;
wire   [0:0] or_ln318_2_fu_510_p2;
wire   [0:0] icmp_ln1547_2_fu_546_p2;
wire   [0:0] and_ln318_3_fu_552_p2;
wire   [16:0] p_Result_32_fu_536_p4;
wire   [16:0] x_l_FH_V_29_fu_530_p2;
wire   [4:0] x_l_I_V_58_fu_522_p3;
wire   [3:0] p_Result_8_fu_582_p4;
wire   [16:0] mul_FH_V_2_fu_592_p5;
wire   [0:0] icmp_ln318_6_fu_603_p2;
wire   [0:0] or_ln318_3_fu_615_p2;
wire   [0:0] icmp_ln1547_3_fu_633_p2;
wire   [16:0] p_Result_33_fu_650_p4;
wire   [4:0] x_l_I_V_60_fu_645_p3;
wire   [16:0] res_FH_V_36_fu_659_p3;
wire   [4:0] p_Result_5_fu_676_p4;
wire   [4:0] x_l_I_V_61_fu_670_p3;
wire   [16:0] x_l_FH_V_32_fu_665_p3;
wire   [16:0] mul_FH_V_3_fu_686_p5;
wire   [0:0] icmp_ln318_16_fu_697_p2;
wire   [0:0] icmp_ln318_17_fu_703_p2;
wire   [4:0] x_l_I_V_16_fu_715_p2;
wire   [0:0] or_ln318_4_fu_709_p2;
wire   [0:0] icmp_ln1547_4_fu_745_p2;
wire   [0:0] and_ln318_5_fu_751_p2;
wire   [16:0] p_Result_34_fu_735_p4;
wire   [16:0] x_l_FH_V_33_fu_729_p2;
wire   [4:0] x_l_I_V_62_fu_721_p3;
wire   [5:0] p_Result_7_fu_781_p4;
wire   [16:0] mul_FH_V_4_fu_791_p5;
wire   [0:0] icmp_ln318_18_fu_802_p2;
wire   [0:0] or_ln318_5_fu_814_p2;
wire   [0:0] icmp_ln1547_5_fu_832_p2;
wire   [16:0] p_Result_35_fu_849_p4;
wire   [4:0] x_l_I_V_64_fu_844_p3;
wire   [16:0] res_FH_V_38_fu_858_p3;
wire   [6:0] p_Result_1_fu_875_p4;
wire   [4:0] x_l_I_V_65_fu_869_p3;
wire   [16:0] x_l_FH_V_36_fu_864_p3;
wire   [16:0] mul_FH_V_5_fu_885_p5;
wire   [0:0] icmp_ln318_20_fu_896_p2;
wire   [0:0] icmp_ln318_21_fu_902_p2;
wire   [4:0] x_l_I_V_22_fu_914_p2;
wire   [0:0] or_ln318_6_fu_908_p2;
wire   [0:0] icmp_ln1547_6_fu_944_p2;
wire   [0:0] and_ln318_7_fu_950_p2;
wire   [16:0] p_Result_36_fu_934_p4;
wire   [16:0] x_l_FH_V_37_fu_928_p2;
wire   [4:0] x_l_I_V_66_fu_920_p3;
wire   [7:0] p_Result_2_fu_980_p4;
wire   [16:0] mul_FH_V_6_fu_990_p5;
wire   [0:0] icmp_ln318_22_fu_1001_p2;
wire   [0:0] or_ln318_7_fu_1013_p2;
wire   [0:0] icmp_ln1547_7_fu_1031_p2;
wire   [16:0] p_Result_37_fu_1048_p4;
wire   [4:0] x_l_I_V_68_fu_1043_p3;
wire   [16:0] res_FH_V_fu_1057_p3;
wire   [8:0] p_Result_3_fu_1074_p4;
wire   [4:0] x_l_I_V_69_fu_1068_p3;
wire   [16:0] x_l_FH_V_40_fu_1063_p3;
wire   [16:0] mul_FH_V_7_fu_1084_p4;
wire   [0:0] icmp_ln1551_fu_1099_p2;
wire   [0:0] icmp_ln1547_9_fu_1105_p2;
wire   [0:0] icmp_ln331_fu_1117_p2;
wire   [0:0] xor_ln331_7_fu_1123_p2;
wire   [4:0] x_l_I_V_28_fu_1129_p2;
wire   [16:0] xor_ln712_fu_1143_p2;
wire   [0:0] icmp_ln1547_8_fu_1093_p2;
wire   [0:0] and_ln318_fu_1111_p2;
wire   [0:0] or_ln318_16_fu_1165_p2;
wire   [16:0] p_Result_38_fu_1155_p4;
wire   [16:0] x_l_FH_V_41_fu_1149_p2;
wire   [4:0] x_l_I_V_70_fu_1135_p3;
wire   [7:0] tmp_7_fu_1213_p4;
wire   [1:0] tmp_fu_1203_p4;
wire   [16:0] mul_FL_V_fu_1232_p3;
wire   [0:0] icmp_ln1547_10_fu_1278_p2;
wire   [0:0] xor_ln1547_1_fu_1284_p2;
wire   [0:0] or_ln318_8_fu_1252_p2;
wire   [0:0] and_ln318_9_fu_1290_p2;
wire   [0:0] icmp_ln1551_1_fu_1272_p2;
wire   [0:0] xor_ln331_fu_1302_p2;
wire   [0:0] icmp_ln1548_fu_1312_p2;
wire   [0:0] or_ln331_fu_1307_p2;
wire   [0:0] xor_ln1548_fu_1316_p2;
wire   [0:0] and_ln331_fu_1322_p2;
wire   [4:0] x_l_I_V_31_fu_1328_p2;
wire   [16:0] sub_ln712_fu_1340_p2;
wire   [16:0] p_Result_39_fu_1349_p4;
wire   [16:0] x_l_FH_V_43_fu_1344_p2;
wire   [4:0] x_l_I_V_72_fu_1333_p3;
wire   [6:0] tmp_9_fu_1391_p4;
wire   [3:0] tmp_2_fu_1381_p4;
wire   [16:0] mul_FH_V_9_fu_1401_p4;
wire   [16:0] mul_FL_V_1_fu_1410_p3;
wire   [16:0] p_neg170_fu_1442_p3;
wire   [16:0] sub_ln712_3_fu_1450_p2;
wire   [0:0] icmp_ln1547_11_fu_1474_p2;
wire   [0:0] xor_ln1547_2_fu_1480_p2;
wire   [0:0] or_ln318_9_fu_1430_p2;
wire   [0:0] and_ln318_11_fu_1486_p2;
wire   [0:0] icmp_ln1551_2_fu_1468_p2;
wire   [0:0] xor_ln331_1_fu_1498_p2;
wire   [0:0] or_ln331_1_fu_1503_p2;
wire   [0:0] xor_ln1548_1_fu_1508_p2;
wire   [0:0] and_ln331_1_fu_1513_p2;
wire   [4:0] x_l_I_V_34_fu_1519_p2;
wire   [16:0] p_Result_40_fu_1531_p4;
wire   [4:0] x_l_I_V_74_fu_1524_p3;
wire   [16:0] res_FH_V_42_fu_1540_p3;
wire   [5:0] tmp_3_fu_1572_p4;
wire   [5:0] tmp_4_fu_1562_p4;
wire   [16:0] mul_FH_V_10_fu_1582_p4;
wire   [16:0] x_l_FL_V_17_fu_1546_p3;
wire   [16:0] mul_FL_V_2_fu_1591_p3;
wire   [0:0] icmp_ln318_10_fu_1599_p2;
wire   [0:0] delta_V_2_fu_1605_p2;
wire   [0:0] xor_ln331_2_fu_1617_p2;
wire   [0:0] icmp_ln1548_2_fu_1629_p2;
wire   [0:0] or_ln331_2_fu_1623_p2;
wire   [0:0] xor_ln1548_2_fu_1635_p2;
wire   [4:0] x_l_I_V_75_fu_1556_p3;
wire   [0:0] and_ln331_2_fu_1641_p2;
wire   [4:0] x_l_I_V_37_fu_1655_p2;
wire   [16:0] p_neg171_fu_1647_p3;
wire   [16:0] sub_ln712_6_fu_1669_p2;
wire   [0:0] icmp_ln1547_12_fu_1703_p2;
wire   [0:0] xor_ln1547_3_fu_1709_p2;
wire   [0:0] or_ln318_10_fu_1611_p2;
wire   [0:0] and_ln318_13_fu_1715_p2;
wire   [0:0] icmp_ln1551_3_fu_1697_p2;
wire   [16:0] p_Result_41_fu_1687_p4;
wire   [16:0] x_l_FL_V_5_fu_1681_p2;
wire   [4:0] x_l_I_V_76_fu_1661_p3;
wire   [16:0] x_l_FH_V_48_fu_1771_p3;
wire   [16:0] mul_FH_V_11_fu_1776_p4;
wire   [16:0] mul_FL_V_3_fu_1784_p3;
wire   [0:0] icmp_ln318_11_fu_1791_p2;
wire   [0:0] delta_V_3_fu_1797_p2;
wire   [0:0] xor_ln331_3_fu_1808_p2;
wire   [0:0] icmp_ln1548_3_fu_1820_p2;
wire   [0:0] or_ln331_3_fu_1814_p2;
wire   [0:0] xor_ln1548_3_fu_1826_p2;
wire   [0:0] and_ln331_3_fu_1832_p2;
wire   [4:0] x_l_I_V_40_fu_1846_p2;
wire   [16:0] p_neg172_fu_1838_p3;
wire   [16:0] sub_ln712_9_fu_1858_p2;
wire   [0:0] icmp_ln1547_13_fu_1889_p2;
wire   [0:0] xor_ln1547_4_fu_1895_p2;
wire   [0:0] or_ln318_11_fu_1802_p2;
wire   [0:0] and_ln318_15_fu_1901_p2;
wire   [0:0] icmp_ln1551_4_fu_1884_p2;
wire   [0:0] and_ln318_16_fu_1907_p2;
wire   [16:0] p_Result_42_fu_1875_p4;
wire   [16:0] x_l_FL_V_7_fu_1870_p2;
wire   [16:0] x_l_FH_V_49_fu_1864_p2;
wire   [4:0] x_l_I_V_78_fu_1851_p3;
wire   [9:0] tmp_8_fu_1942_p4;
wire   [16:0] mul_FH_V_12_fu_1984_p4;
wire   [0:0] icmp_ln318_12_fu_1992_p2;
wire   [0:0] xor_ln331_4_fu_2002_p2;
wire   [0:0] icmp_ln1548_4_fu_2013_p2;
wire   [0:0] or_ln331_4_fu_2007_p2;
wire   [0:0] xor_ln1548_4_fu_2018_p2;
wire   [0:0] and_ln331_4_fu_2024_p2;
wire   [4:0] x_l_I_V_43_fu_2030_p2;
wire   [16:0] sub_ln712_12_fu_2042_p2;
wire   [0:0] icmp_ln1547_14_fu_2070_p2;
wire   [0:0] xor_ln1547_5_fu_2075_p2;
wire   [0:0] or_ln318_12_fu_1997_p2;
wire   [0:0] and_ln318_17_fu_2081_p2;
wire   [0:0] icmp_ln1551_5_fu_2065_p2;
wire   [0:0] and_ln318_18_fu_2087_p2;
wire   [16:0] p_Result_43_fu_2056_p4;
wire   [16:0] x_l_FL_V_9_fu_2052_p2;
wire   [16:0] x_l_FH_V_51_fu_2047_p2;
wire   [4:0] x_l_I_V_80_fu_2035_p3;
wire   [2:0] tmp_11_fu_2131_p4;
wire   [11:0] tmp_s_fu_2121_p4;
wire   [16:0] mul_FL_V_5_fu_2150_p3;
wire   [0:0] icmp_ln1547_15_fu_2196_p2;
wire   [0:0] xor_ln1547_6_fu_2202_p2;
wire   [0:0] or_ln318_13_fu_2170_p2;
wire   [0:0] and_ln318_19_fu_2208_p2;
wire   [0:0] icmp_ln1551_6_fu_2190_p2;
wire   [0:0] xor_ln331_5_fu_2220_p2;
wire   [0:0] icmp_ln1548_5_fu_2230_p2;
wire   [0:0] or_ln331_5_fu_2225_p2;
wire   [0:0] xor_ln1548_5_fu_2234_p2;
wire   [0:0] and_ln331_5_fu_2240_p2;
wire   [4:0] x_l_I_V_46_fu_2246_p2;
wire   [16:0] sub_ln712_15_fu_2258_p2;
wire   [16:0] p_Result_44_fu_2267_p4;
wire   [16:0] x_l_FH_V_53_fu_2262_p2;
wire   [4:0] x_l_I_V_82_fu_2251_p3;
wire   [1:0] tmp_12_fu_2309_p4;
wire   [13:0] tmp_1_fu_2299_p4;
wire   [16:0] mul_FH_V_14_fu_2319_p4;
wire   [16:0] p_neg175_fu_2360_p3;
wire   [16:0] sub_ln712_18_fu_2368_p2;
wire   [0:0] icmp_ln1547_16_fu_2386_p2;
wire   [0:0] xor_ln1547_7_fu_2392_p2;
wire   [0:0] or_ln318_14_fu_2348_p2;
wire   [0:0] and_ln318_21_fu_2398_p2;
wire   [0:0] icmp_ln1551_7_fu_2380_p2;
wire   [0:0] xor_ln331_6_fu_2417_p2;
wire   [0:0] or_ln331_6_fu_2422_p2;
wire   [0:0] xor_ln1548_6_fu_2427_p2;
wire   [0:0] and_ln331_6_fu_2432_p2;
wire   [4:0] x_l_I_V_49_fu_2438_p2;
wire   [16:0] p_Result_45_fu_2454_p4;
wire   [16:0] x_l_FL_V_13_fu_2450_p2;
wire   [4:0] x_l_I_V_84_fu_2443_p3;
wire   [16:0] res_FH_V_47_fu_2463_p3;
wire   [15:0] trunc_ln104_fu_2486_p1;
wire   [0:0] tmp_33_fu_2498_p3;
wire   [16:0] x_l_FH_V_56_fu_2475_p3;
wire   [16:0] mul_FH_V_15_fu_2506_p4;
wire   [16:0] x_l_FL_V_14_fu_2469_p3;
wire   [16:0] mul_FL_V_7_fu_2490_p3;
wire   [0:0] icmp_ln318_15_fu_2515_p2;
wire   [0:0] icmp_ln1549_fu_2521_p2;
wire   [4:0] x_l_I_V_85_fu_2480_p3;
wire   [0:0] icmp_ln1547_17_fu_2549_p2;
wire   [0:0] xor_ln1547_8_fu_2555_p2;
wire   [0:0] or_ln318_15_fu_2527_p2;
wire   [0:0] and_ln318_23_fu_2561_p2;
wire   [0:0] icmp_ln1551_8_fu_2543_p2;
wire   [0:0] and_ln318_24_fu_2567_p2;
wire   [16:0] p_Result_46_fu_2533_p4;
wire   [16:0] res_FH_V_31_fu_2573_p3;
wire   [17:0] zext_ln712_1_fu_2581_p1;
wire   [17:0] res_FH_l_V_fu_2585_p2;
wire   [0:0] p_Result_27_fu_2597_p3;
wire   [16:0] res_FH_V_48_fu_2591_p2;
wire   [0:0] res_I_V_3_fu_2605_p3;
wire   [15:0] tmp_13_fu_2611_p4;
wire   [0:0] p_Result_s_fu_2410_p3;
wire   [16:0] trunc_ln3_fu_2621_p3;
reg   [17:0] x_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln318_10_reg_2868 <= and_ln318_10_fu_1296_p2;
        and_ln318_12_reg_2924 <= and_ln318_12_fu_1492_p2;
        and_ln318_14_reg_2942 <= and_ln318_14_fu_1721_p2;
        and_ln318_20_reg_3079 <= and_ln318_20_fu_2214_p2;
        and_ln318_22_reg_3136 <= and_ln318_22_fu_2404_p2;
        and_ln318_2_reg_2693 <= and_ln318_2_fu_428_p2;
        and_ln318_4_reg_2732 <= and_ln318_4_fu_639_p2;
        and_ln318_6_reg_2771 <= and_ln318_6_fu_838_p2;
        and_ln318_8_reg_2810 <= and_ln318_8_fu_1037_p2;
        delta_V_1_reg_2904 <= delta_V_1_fu_1424_p2;
        delta_V_4_reg_3017 <= delta_V_4_fu_1970_p2;
        delta_V_5_reg_3064 <= delta_V_5_fu_2164_p2;
        delta_V_6_reg_3121 <= delta_V_6_fu_2342_p2;
        delta_V_reg_2853 <= delta_V_fu_1246_p2;
        icmp_ln1548_1_reg_2909 <= icmp_ln1548_1_fu_1436_p2;
        icmp_ln1548_6_reg_3126 <= icmp_ln1548_6_fu_2354_p2;
        icmp_ln318_13_reg_3059 <= icmp_ln318_13_fu_2158_p2;
        icmp_ln318_14_reg_3116 <= icmp_ln318_14_fu_2336_p2;
        icmp_ln318_19_reg_2756 <= icmp_ln318_19_fu_808_p2;
        icmp_ln318_23_reg_2795 <= icmp_ln318_23_fu_1007_p2;
        icmp_ln318_3_reg_2683 <= icmp_ln318_3_fu_404_p2;
        icmp_ln318_7_reg_2717 <= icmp_ln318_7_fu_609_p2;
        icmp_ln318_8_reg_2848 <= icmp_ln318_8_fu_1240_p2;
        icmp_ln318_9_reg_2899 <= icmp_ln318_9_fu_1418_p2;
        mul_FH_V_13_reg_3053[3 : 0] <= mul_FH_V_13_fu_2141_p4[3 : 0];
        mul_FH_V_8_reg_2842[8 : 0] <= mul_FH_V_8_fu_1223_p4[8 : 0];
        mul_FL_V_4_reg_3012[16 : 7] <= mul_FL_V_4_fu_1962_p3[16 : 7];
        mul_FL_V_6_reg_3111[16 : 3] <= mul_FL_V_6_fu_2328_p3[16 : 3];
        p_Val2_9_reg_2673[16 : 1] <= p_Val2_9_fu_362_p3[16 : 1];
        p_neg169_reg_2858 <= p_neg169_fu_1258_p3;
        p_neg173_reg_3023 <= p_neg173_fu_1976_p3;
        p_neg174_reg_3069 <= p_neg174_fu_2176_p3;
        res_FH_V_33_reg_2667[16] <= res_FH_V_33_fu_354_p3[16];
        res_FH_V_35_reg_2700 <= res_FH_V_35_fu_558_p3;
        res_FH_V_37_reg_2739 <= res_FH_V_37_fu_757_p3;
        res_FH_V_39_reg_2778 <= res_FH_V_39_fu_956_p3;
        res_FH_V_40_reg_2817 <= res_FH_V_40_fu_1171_p3;
        res_FH_V_41_reg_2876 <= res_FH_V_41_fu_1358_p3;
        res_FH_V_43_reg_2947 <= res_FH_V_43_fu_1727_p3;
        res_FH_V_44_reg_2978 <= res_FH_V_44_fu_1913_p3;
        res_FH_V_45_reg_3028 <= res_FH_V_45_fu_2093_p3;
        res_FH_V_46_reg_3087 <= res_FH_V_46_fu_2276_p3;
        res_I_V_2_reg_2647 <= res_I_V_2_fu_264_p2;
        res_I_V_2_reg_2647_pp0_iter1_reg <= res_I_V_2_reg_2647;
        res_I_V_2_reg_2647_pp0_iter2_reg <= res_I_V_2_reg_2647_pp0_iter1_reg;
        res_I_V_2_reg_2647_pp0_iter3_reg <= res_I_V_2_reg_2647_pp0_iter2_reg;
        res_I_V_2_reg_2647_pp0_iter4_reg <= res_I_V_2_reg_2647_pp0_iter3_reg;
        res_I_V_2_reg_2647_pp0_iter5_reg <= res_I_V_2_reg_2647_pp0_iter4_reg;
        res_I_V_2_reg_2647_pp0_iter6_reg <= res_I_V_2_reg_2647_pp0_iter5_reg;
        res_I_V_2_reg_2647_pp0_iter7_reg <= res_I_V_2_reg_2647_pp0_iter6_reg;
        res_I_V_2_reg_2647_pp0_iter8_reg <= res_I_V_2_reg_2647_pp0_iter7_reg;
        res_I_V_2_reg_2647_pp0_iter9_reg <= res_I_V_2_reg_2647_pp0_iter8_reg;
        res_I_V_reg_2642 <= res_I_V_fu_240_p2;
        res_I_V_reg_2642_pp0_iter1_reg <= res_I_V_reg_2642;
        res_I_V_reg_2642_pp0_iter2_reg <= res_I_V_reg_2642_pp0_iter1_reg;
        res_I_V_reg_2642_pp0_iter3_reg <= res_I_V_reg_2642_pp0_iter2_reg;
        res_I_V_reg_2642_pp0_iter4_reg <= res_I_V_reg_2642_pp0_iter3_reg;
        res_I_V_reg_2642_pp0_iter5_reg <= res_I_V_reg_2642_pp0_iter4_reg;
        res_I_V_reg_2642_pp0_iter6_reg <= res_I_V_reg_2642_pp0_iter5_reg;
        res_I_V_reg_2642_pp0_iter7_reg <= res_I_V_reg_2642_pp0_iter6_reg;
        res_I_V_reg_2642_pp0_iter8_reg <= res_I_V_reg_2642_pp0_iter7_reg;
        res_I_V_reg_2642_pp0_iter9_reg <= res_I_V_reg_2642_pp0_iter8_reg;
        tmp_10_reg_3007 <= {{res_FH_V_44_fu_1913_p3[16:13]}};
        tmp_5_reg_2973 <= {{res_FH_V_43_fu_1727_p3[16:12]}};
        tmp_6_reg_2968 <= {{res_FH_V_43_fu_1727_p3[11:4]}};
        x_l_FH_V_27_reg_2688[16 : 1] <= x_l_FH_V_27_fu_416_p2[16 : 1];
        x_l_FH_V_30_reg_2706[16 : 1] <= x_l_FH_V_30_fu_566_p3[16 : 1];
        x_l_FH_V_31_reg_2727[16 : 1] <= x_l_FH_V_31_fu_627_p2[16 : 1];
        x_l_FH_V_34_reg_2745[16 : 1] <= x_l_FH_V_34_fu_765_p3[16 : 1];
        x_l_FH_V_35_reg_2766[16 : 1] <= x_l_FH_V_35_fu_826_p2[16 : 1];
        x_l_FH_V_38_reg_2784[16 : 1] <= x_l_FH_V_38_fu_964_p3[16 : 1];
        x_l_FH_V_39_reg_2805[16 : 1] <= x_l_FH_V_39_fu_1025_p2[16 : 1];
        x_l_FH_V_42_reg_2828 <= x_l_FH_V_42_fu_1187_p3;
        x_l_FH_V_44_reg_2887 <= x_l_FH_V_44_fu_1369_p3;
        x_l_FH_V_45_reg_2914 <= x_l_FH_V_45_fu_1456_p2;
        x_l_FH_V_46_reg_2932 <= x_l_FH_V_46_fu_1551_p3;
        x_l_FH_V_47_reg_2937 <= x_l_FH_V_47_fu_1675_p2;
        x_l_FH_V_50_reg_2990 <= x_l_FH_V_50_fu_1927_p3;
        x_l_FH_V_52_reg_3039 <= x_l_FH_V_52_fu_2107_p3;
        x_l_FH_V_54_reg_3099 <= x_l_FH_V_54_fu_2287_p3;
        x_l_FH_V_55_reg_3131 <= x_l_FH_V_55_fu_2374_p2;
        x_l_FL_V_11_reg_3074[16 : 5] <= x_l_FL_V_11_fu_2184_p2[16 : 5];
        x_l_FL_V_15_reg_2823[16] <= x_l_FL_V_15_fu_1179_p3[16];
        x_l_FL_V_16_reg_2882[16 : 14] <= x_l_FL_V_16_fu_1364_p3[16 : 14];
        x_l_FL_V_18_reg_2953[16 : 10] <= x_l_FL_V_18_fu_1735_p3[16 : 10];
        x_l_FL_V_19_reg_2984[16 : 8] <= x_l_FL_V_19_fu_1920_p3[16 : 8];
        x_l_FL_V_20_reg_3034[16 : 6] <= x_l_FL_V_20_fu_2100_p3[16 : 6];
        x_l_FL_V_21_reg_3093[16 : 4] <= x_l_FL_V_21_fu_2282_p3[16 : 4];
        x_l_FL_V_3_reg_2919[16 : 13] <= x_l_FL_V_3_fu_1462_p2[16 : 13];
        x_l_FL_V_reg_2863[16 : 15] <= x_l_FL_V_fu_1266_p2[16 : 15];
        x_l_I_V_13_reg_2722 <= x_l_I_V_13_fu_621_p2;
        x_l_I_V_19_reg_2761 <= x_l_I_V_19_fu_820_p2;
        x_l_I_V_25_reg_2800 <= x_l_I_V_25_fu_1019_p2;
        x_l_I_V_55_reg_2678 <= x_l_I_V_55_fu_370_p3;
        x_l_I_V_59_reg_2711 <= x_l_I_V_59_fu_574_p3;
        x_l_I_V_63_reg_2750 <= x_l_I_V_63_fu_773_p3;
        x_l_I_V_67_reg_2789 <= x_l_I_V_67_fu_972_p3;
        x_l_I_V_71_reg_2835 <= x_l_I_V_71_fu_1195_p3;
        x_l_I_V_73_reg_2892 <= x_l_I_V_73_fu_1375_p3;
        x_l_I_V_77_reg_2960 <= x_l_I_V_77_fu_1743_p3;
        x_l_I_V_79_reg_2999 <= x_l_I_V_79_fu_1935_p3;
        x_l_I_V_81_reg_3046 <= x_l_I_V_81_fu_2114_p3;
        x_l_I_V_83_reg_3104 <= x_l_I_V_83_fu_2293_p3;
        x_read_reg_2637 <= x_int_reg;
        x_read_reg_2637_pp0_iter1_reg <= x_read_reg_2637;
        x_read_reg_2637_pp0_iter2_reg <= x_read_reg_2637_pp0_iter1_reg;
        x_read_reg_2637_pp0_iter3_reg <= x_read_reg_2637_pp0_iter2_reg;
        x_read_reg_2637_pp0_iter4_reg <= x_read_reg_2637_pp0_iter3_reg;
        x_read_reg_2637_pp0_iter5_reg <= x_read_reg_2637_pp0_iter4_reg;
        x_read_reg_2637_pp0_iter6_reg <= x_read_reg_2637_pp0_iter5_reg;
        x_read_reg_2637_pp0_iter7_reg <= x_read_reg_2637_pp0_iter6_reg;
        x_read_reg_2637_pp0_iter8_reg <= x_read_reg_2637_pp0_iter7_reg;
        x_read_reg_2637_pp0_iter9_reg <= x_read_reg_2637_pp0_iter8_reg;
    end
end

assign and_ln318_10_fu_1296_p2 = (icmp_ln1551_1_fu_1272_p2 & and_ln318_9_fu_1290_p2);

assign and_ln318_11_fu_1486_p2 = (xor_ln1547_2_fu_1480_p2 & or_ln318_9_fu_1430_p2);

assign and_ln318_12_fu_1492_p2 = (icmp_ln1551_2_fu_1468_p2 & and_ln318_11_fu_1486_p2);

assign and_ln318_13_fu_1715_p2 = (xor_ln1547_3_fu_1709_p2 & or_ln318_10_fu_1611_p2);

assign and_ln318_14_fu_1721_p2 = (icmp_ln1551_3_fu_1697_p2 & and_ln318_13_fu_1715_p2);

assign and_ln318_15_fu_1901_p2 = (xor_ln1547_4_fu_1895_p2 & or_ln318_11_fu_1802_p2);

assign and_ln318_16_fu_1907_p2 = (icmp_ln1551_4_fu_1884_p2 & and_ln318_15_fu_1901_p2);

assign and_ln318_17_fu_2081_p2 = (xor_ln1547_5_fu_2075_p2 & or_ln318_12_fu_1997_p2);

assign and_ln318_18_fu_2087_p2 = (icmp_ln1551_5_fu_2065_p2 & and_ln318_17_fu_2081_p2);

assign and_ln318_19_fu_2208_p2 = (xor_ln1547_6_fu_2202_p2 & or_ln318_13_fu_2170_p2);

assign and_ln318_1_fu_348_p2 = (xor_ln1547_fu_342_p2 & or_ln318_fu_300_p2);

assign and_ln318_20_fu_2214_p2 = (icmp_ln1551_6_fu_2190_p2 & and_ln318_19_fu_2208_p2);

assign and_ln318_21_fu_2398_p2 = (xor_ln1547_7_fu_2392_p2 & or_ln318_14_fu_2348_p2);

assign and_ln318_22_fu_2404_p2 = (icmp_ln1551_7_fu_2380_p2 & and_ln318_21_fu_2398_p2);

assign and_ln318_23_fu_2561_p2 = (xor_ln1547_8_fu_2555_p2 & or_ln318_15_fu_2527_p2);

assign and_ln318_24_fu_2567_p2 = (icmp_ln1551_8_fu_2543_p2 & and_ln318_23_fu_2561_p2);

assign and_ln318_2_fu_428_p2 = (or_ln318_1_fu_410_p2 & icmp_ln1547_1_fu_422_p2);

assign and_ln318_3_fu_552_p2 = (or_ln318_2_fu_510_p2 & icmp_ln1547_2_fu_546_p2);

assign and_ln318_4_fu_639_p2 = (or_ln318_3_fu_615_p2 & icmp_ln1547_3_fu_633_p2);

assign and_ln318_5_fu_751_p2 = (or_ln318_4_fu_709_p2 & icmp_ln1547_4_fu_745_p2);

assign and_ln318_6_fu_838_p2 = (or_ln318_5_fu_814_p2 & icmp_ln1547_5_fu_832_p2);

assign and_ln318_7_fu_950_p2 = (or_ln318_6_fu_908_p2 & icmp_ln1547_6_fu_944_p2);

assign and_ln318_8_fu_1037_p2 = (or_ln318_7_fu_1013_p2 & icmp_ln1547_7_fu_1031_p2);

assign and_ln318_9_fu_1290_p2 = (xor_ln1547_1_fu_1284_p2 & or_ln318_8_fu_1252_p2);

assign and_ln318_fu_1111_p2 = (icmp_ln1551_fu_1099_p2 & icmp_ln1547_9_fu_1105_p2);

assign and_ln331_1_fu_1513_p2 = (xor_ln1548_1_fu_1508_p2 & or_ln331_1_fu_1503_p2);

assign and_ln331_2_fu_1641_p2 = (xor_ln1548_2_fu_1635_p2 & or_ln331_2_fu_1623_p2);

assign and_ln331_3_fu_1832_p2 = (xor_ln1548_3_fu_1826_p2 & or_ln331_3_fu_1814_p2);

assign and_ln331_4_fu_2024_p2 = (xor_ln1548_4_fu_2018_p2 & or_ln331_4_fu_2007_p2);

assign and_ln331_5_fu_2240_p2 = (xor_ln1548_5_fu_2234_p2 & or_ln331_5_fu_2225_p2);

assign and_ln331_6_fu_2432_p2 = (xor_ln1548_6_fu_2427_p2 & or_ln331_6_fu_2422_p2);

assign and_ln331_fu_1322_p2 = (xor_ln1548_fu_1316_p2 & or_ln331_fu_1307_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_s_fu_2410_p3[0:0] == 1'b1) ? 17'd0 : trunc_ln3_fu_2621_p3);

assign delta_V_1_fu_1424_p2 = ((x_l_FL_V_16_fu_1364_p3 < mul_FL_V_1_fu_1410_p3) ? 1'b1 : 1'b0);

assign delta_V_2_fu_1605_p2 = ((x_l_FL_V_17_fu_1546_p3 < mul_FL_V_2_fu_1591_p3) ? 1'b1 : 1'b0);

assign delta_V_3_fu_1797_p2 = ((x_l_FL_V_18_reg_2953 < mul_FL_V_3_fu_1784_p3) ? 1'b1 : 1'b0);

assign delta_V_4_fu_1970_p2 = ((x_l_FL_V_19_fu_1920_p3 < mul_FL_V_4_fu_1962_p3) ? 1'b1 : 1'b0);

assign delta_V_5_fu_2164_p2 = ((x_l_FL_V_20_fu_2100_p3 < mul_FL_V_5_fu_2150_p3) ? 1'b1 : 1'b0);

assign delta_V_6_fu_2342_p2 = ((x_l_FL_V_21_fu_2282_p3 < mul_FL_V_6_fu_2328_p3) ? 1'b1 : 1'b0);

assign delta_V_fu_1246_p2 = ((x_l_FL_V_15_fu_1179_p3 < mul_FL_V_fu_1232_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_10_fu_1278_p2 = ((mul_FH_V_8_fu_1223_p4 < x_l_FH_V_42_fu_1187_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_11_fu_1474_p2 = ((mul_FH_V_9_fu_1401_p4 < x_l_FH_V_44_fu_1369_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_12_fu_1703_p2 = ((mul_FH_V_10_fu_1582_p4 < x_l_FH_V_46_fu_1551_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_13_fu_1889_p2 = ((mul_FH_V_11_fu_1776_p4 < x_l_FH_V_48_fu_1771_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_14_fu_2070_p2 = ((mul_FH_V_12_fu_1984_p4 < x_l_FH_V_50_reg_2990) ? 1'b1 : 1'b0);

assign icmp_ln1547_15_fu_2196_p2 = ((mul_FH_V_13_fu_2141_p4 < x_l_FH_V_52_fu_2107_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_16_fu_2386_p2 = ((mul_FH_V_14_fu_2319_p4 < x_l_FH_V_54_fu_2287_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_17_fu_2549_p2 = ((mul_FH_V_15_fu_2506_p4 < x_l_FH_V_56_fu_2475_p3) ? 1'b1 : 1'b0);

assign icmp_ln1547_1_fu_422_p2 = ((x_l_I_V_55_fu_370_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_2_fu_546_p2 = ((x_l_I_V_57_fu_470_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_3_fu_633_p2 = ((x_l_I_V_59_fu_574_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_4_fu_745_p2 = ((x_l_I_V_61_fu_670_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_5_fu_832_p2 = ((x_l_I_V_63_fu_773_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_6_fu_944_p2 = ((x_l_I_V_65_fu_869_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_7_fu_1031_p2 = ((x_l_I_V_67_fu_972_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_8_fu_1093_p2 = ((x_l_I_V_69_fu_1068_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1547_9_fu_1105_p2 = ((x_l_FH_V_40_fu_1063_p3 > mul_FH_V_7_fu_1084_p4) ? 1'b1 : 1'b0);

assign icmp_ln1547_fu_336_p2 = ((trunc_ln1_fu_270_p3 < x_l_I_V_53_fu_252_p3) ? 1'b1 : 1'b0);

assign icmp_ln1548_1_fu_1436_p2 = ((x_l_FH_V_44_fu_1369_p3 < mul_FH_V_9_fu_1401_p4) ? 1'b1 : 1'b0);

assign icmp_ln1548_2_fu_1629_p2 = ((x_l_FH_V_46_fu_1551_p3 < mul_FH_V_10_fu_1582_p4) ? 1'b1 : 1'b0);

assign icmp_ln1548_3_fu_1820_p2 = ((x_l_FH_V_48_fu_1771_p3 < mul_FH_V_11_fu_1776_p4) ? 1'b1 : 1'b0);

assign icmp_ln1548_4_fu_2013_p2 = ((x_l_FH_V_50_reg_2990 < mul_FH_V_12_fu_1984_p4) ? 1'b1 : 1'b0);

assign icmp_ln1548_5_fu_2230_p2 = ((x_l_FH_V_52_reg_3039 < mul_FH_V_13_reg_3053) ? 1'b1 : 1'b0);

assign icmp_ln1548_6_fu_2354_p2 = ((x_l_FH_V_54_fu_2287_p3 < mul_FH_V_14_fu_2319_p4) ? 1'b1 : 1'b0);

assign icmp_ln1548_fu_1312_p2 = ((x_l_FH_V_42_reg_2828 < mul_FH_V_8_reg_2842) ? 1'b1 : 1'b0);

assign icmp_ln1549_fu_2521_p2 = ((x_l_FL_V_14_fu_2469_p3 < mul_FL_V_7_fu_2490_p3) ? 1'b1 : 1'b0);

assign icmp_ln1551_1_fu_1272_p2 = ((x_l_I_V_71_fu_1195_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_2_fu_1468_p2 = ((x_l_I_V_73_fu_1375_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_3_fu_1697_p2 = ((x_l_I_V_75_fu_1556_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_4_fu_1884_p2 = ((x_l_I_V_77_reg_2960 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_5_fu_2065_p2 = ((x_l_I_V_79_reg_2999 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_6_fu_2190_p2 = ((x_l_I_V_81_fu_2114_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_7_fu_2380_p2 = ((x_l_I_V_83_fu_2293_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_8_fu_2543_p2 = ((x_l_I_V_85_fu_2480_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1551_fu_1099_p2 = ((x_l_I_V_69_fu_1068_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_10_fu_1599_p2 = ((x_l_FH_V_46_fu_1551_p3 != mul_FH_V_10_fu_1582_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_11_fu_1791_p2 = ((x_l_FH_V_48_fu_1771_p3 != mul_FH_V_11_fu_1776_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_12_fu_1992_p2 = ((x_l_FH_V_50_reg_2990 != mul_FH_V_12_fu_1984_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_13_fu_2158_p2 = ((x_l_FH_V_52_fu_2107_p3 != mul_FH_V_13_fu_2141_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_14_fu_2336_p2 = ((x_l_FH_V_54_fu_2287_p3 != mul_FH_V_14_fu_2319_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_15_fu_2515_p2 = ((x_l_FH_V_56_fu_2475_p3 != mul_FH_V_15_fu_2506_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_16_fu_697_p2 = ((x_l_I_V_61_fu_670_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_17_fu_703_p2 = ((x_l_FH_V_32_fu_665_p3 < mul_FH_V_3_fu_686_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_18_fu_802_p2 = ((x_l_I_V_63_fu_773_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_19_fu_808_p2 = ((x_l_FH_V_34_fu_765_p3 < mul_FH_V_4_fu_791_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_294_p2 = ((tmp_15_fu_284_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_20_fu_896_p2 = ((x_l_I_V_65_fu_869_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_21_fu_902_p2 = ((x_l_FH_V_36_fu_864_p3 < mul_FH_V_5_fu_885_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_22_fu_1001_p2 = ((x_l_I_V_67_fu_972_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_23_fu_1007_p2 = ((x_l_FH_V_38_fu_964_p3 < mul_FH_V_6_fu_990_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_398_p2 = ((x_l_I_V_55_fu_370_p3 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_404_p2 = ((p_Val2_9_fu_362_p3 < mul_FH_V_fu_388_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_498_p2 = ((x_l_I_V_57_fu_470_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_504_p2 = ((x_l_FH_V_28_fu_465_p3 < mul_FH_V_1_fu_487_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_603_p2 = ((x_l_I_V_59_fu_574_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_609_p2 = ((x_l_FH_V_30_fu_566_p3 < mul_FH_V_2_fu_592_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_1240_p2 = ((x_l_FH_V_42_fu_1187_p3 != mul_FH_V_8_fu_1223_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_1418_p2 = ((x_l_FH_V_44_fu_1369_p3 != mul_FH_V_9_fu_1401_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_278_p2 = ((x_l_I_V_53_fu_252_p3 != trunc_ln1_fu_270_p3) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_1117_p2 = ((mul_FH_V_7_fu_1084_p4 < x_l_FH_V_40_fu_1063_p3) ? 1'b1 : 1'b0);

assign mul_FH_V_10_fu_1582_p4 = {{{{10'd0}, {res_I_V_2_reg_2647_pp0_iter5_reg}}}, {tmp_3_fu_1572_p4}};

assign mul_FH_V_11_fu_1776_p4 = {{{{11'd0}, {res_I_V_2_reg_2647_pp0_iter6_reg}}}, {tmp_5_reg_2973}};

assign mul_FH_V_12_fu_1984_p4 = {{{{12'd0}, {res_I_V_2_reg_2647_pp0_iter7_reg}}}, {tmp_10_reg_3007}};

assign mul_FH_V_13_fu_2141_p4 = {{{{13'd0}, {res_I_V_2_reg_2647_pp0_iter7_reg}}}, {tmp_11_fu_2131_p4}};

assign mul_FH_V_14_fu_2319_p4 = {{{{14'd0}, {res_I_V_2_reg_2647_pp0_iter8_reg}}}, {tmp_12_fu_2309_p4}};

assign mul_FH_V_15_fu_2506_p4 = {{{{15'd0}, {res_I_V_2_reg_2647_pp0_iter9_reg}}}, {tmp_33_fu_2498_p3}};

assign mul_FH_V_1_fu_487_p5 = {{{{{{1'd0}, {res_I_V_2_reg_2647}}}, {p_Result_4_fu_477_p4}}}, {12'd2048}};

assign mul_FH_V_2_fu_592_p5 = {{{{{{2'd0}, {res_I_V_2_reg_2647}}}, {p_Result_8_fu_582_p4}}}, {10'd512}};

assign mul_FH_V_3_fu_686_p5 = {{{{{{3'd0}, {res_I_V_2_reg_2647_pp0_iter1_reg}}}, {p_Result_5_fu_676_p4}}}, {8'd128}};

assign mul_FH_V_4_fu_791_p5 = {{{{{{4'd0}, {res_I_V_2_reg_2647_pp0_iter1_reg}}}, {p_Result_7_fu_781_p4}}}, {6'd32}};

assign mul_FH_V_5_fu_885_p5 = {{{{{{5'd0}, {res_I_V_2_reg_2647_pp0_iter2_reg}}}, {p_Result_1_fu_875_p4}}}, {4'd8}};

assign mul_FH_V_6_fu_990_p5 = {{{{{{6'd0}, {res_I_V_2_reg_2647_pp0_iter2_reg}}}, {p_Result_2_fu_980_p4}}}, {2'd2}};

assign mul_FH_V_7_fu_1084_p4 = {{{{7'd0}, {res_I_V_2_reg_2647_pp0_iter3_reg}}}, {p_Result_3_fu_1074_p4}};

assign mul_FH_V_8_fu_1223_p4 = {{{{8'd0}, {res_I_V_2_reg_2647_pp0_iter3_reg}}}, {tmp_7_fu_1213_p4}};

assign mul_FH_V_9_fu_1401_p4 = {{{{9'd0}, {res_I_V_2_reg_2647_pp0_iter4_reg}}}, {tmp_9_fu_1391_p4}};

assign mul_FH_V_fu_388_p4 = {{{res_I_V_2_fu_264_p2}, {p_Result_s_96_fu_378_p4}}, {14'd8192}};

assign mul_FL_V_1_fu_1410_p3 = {{tmp_2_fu_1381_p4}, {13'd4096}};

assign mul_FL_V_2_fu_1591_p3 = {{tmp_4_fu_1562_p4}, {11'd1024}};

assign mul_FL_V_3_fu_1784_p3 = {{tmp_6_reg_2968}, {9'd256}};

assign mul_FL_V_4_fu_1962_p3 = {{tmp_8_fu_1942_p4}, {7'd64}};

assign mul_FL_V_5_fu_2150_p3 = {{tmp_s_fu_2121_p4}, {5'd16}};

assign mul_FL_V_6_fu_2328_p3 = {{tmp_1_fu_2299_p4}, {3'd4}};

assign mul_FL_V_7_fu_2490_p3 = {{trunc_ln104_fu_2486_p1}, {1'd1}};

assign mul_FL_V_fu_1232_p3 = {{tmp_fu_1203_p4}, {15'd16384}};

assign or_ln318_10_fu_1611_p2 = (icmp_ln318_10_fu_1599_p2 | delta_V_2_fu_1605_p2);

assign or_ln318_11_fu_1802_p2 = (icmp_ln318_11_fu_1791_p2 | delta_V_3_fu_1797_p2);

assign or_ln318_12_fu_1997_p2 = (icmp_ln318_12_fu_1992_p2 | delta_V_4_reg_3017);

assign or_ln318_13_fu_2170_p2 = (icmp_ln318_13_fu_2158_p2 | delta_V_5_fu_2164_p2);

assign or_ln318_14_fu_2348_p2 = (icmp_ln318_14_fu_2336_p2 | delta_V_6_fu_2342_p2);

assign or_ln318_15_fu_2527_p2 = (icmp_ln318_15_fu_2515_p2 | icmp_ln1549_fu_2521_p2);

assign or_ln318_16_fu_1165_p2 = (icmp_ln1547_8_fu_1093_p2 | and_ln318_fu_1111_p2);

assign or_ln318_1_fu_410_p2 = (icmp_ln318_3_fu_404_p2 | icmp_ln318_2_fu_398_p2);

assign or_ln318_2_fu_510_p2 = (icmp_ln318_5_fu_504_p2 | icmp_ln318_4_fu_498_p2);

assign or_ln318_3_fu_615_p2 = (icmp_ln318_7_fu_609_p2 | icmp_ln318_6_fu_603_p2);

assign or_ln318_4_fu_709_p2 = (icmp_ln318_17_fu_703_p2 | icmp_ln318_16_fu_697_p2);

assign or_ln318_5_fu_814_p2 = (icmp_ln318_19_fu_808_p2 | icmp_ln318_18_fu_802_p2);

assign or_ln318_6_fu_908_p2 = (icmp_ln318_21_fu_902_p2 | icmp_ln318_20_fu_896_p2);

assign or_ln318_7_fu_1013_p2 = (icmp_ln318_23_fu_1007_p2 | icmp_ln318_22_fu_1001_p2);

assign or_ln318_8_fu_1252_p2 = (icmp_ln318_8_fu_1240_p2 | delta_V_fu_1246_p2);

assign or_ln318_9_fu_1430_p2 = (icmp_ln318_9_fu_1418_p2 | delta_V_1_fu_1424_p2);

assign or_ln318_fu_300_p2 = (icmp_ln318_fu_278_p2 | icmp_ln318_1_fu_294_p2);

assign or_ln331_1_fu_1503_p2 = (xor_ln331_1_fu_1498_p2 | icmp_ln318_9_reg_2899);

assign or_ln331_2_fu_1623_p2 = (xor_ln331_2_fu_1617_p2 | icmp_ln318_10_fu_1599_p2);

assign or_ln331_3_fu_1814_p2 = (xor_ln331_3_fu_1808_p2 | icmp_ln318_11_fu_1791_p2);

assign or_ln331_4_fu_2007_p2 = (xor_ln331_4_fu_2002_p2 | icmp_ln318_12_fu_1992_p2);

assign or_ln331_5_fu_2225_p2 = (xor_ln331_5_fu_2220_p2 | icmp_ln318_13_reg_3059);

assign or_ln331_6_fu_2422_p2 = (xor_ln331_6_fu_2417_p2 | icmp_ln318_14_reg_3116);

assign or_ln331_fu_1307_p2 = (xor_ln331_fu_1302_p2 | icmp_ln318_8_reg_2848);

assign p_Result_1_fu_875_p4 = {{res_FH_V_38_fu_858_p3[16:10]}};

assign p_Result_27_fu_2597_p3 = res_FH_l_V_fu_2585_p2[32'd17];

assign p_Result_2_fu_980_p4 = {{res_FH_V_39_fu_956_p3[16:9]}};

assign p_Result_30_fu_246_p2 = ($signed(zext_ln235_fu_224_p1) + $signed(3'd7));

assign p_Result_31_fu_450_p4 = {res_FH_V_33_reg_2667[17 - 1:16], |(1'd1), res_FH_V_33_reg_2667[14:0]};

assign p_Result_32_fu_536_p4 = {res_FH_V_34_fu_459_p3[17 - 1:15], |(1'd1), res_FH_V_34_fu_459_p3[13:0]};

assign p_Result_33_fu_650_p4 = {res_FH_V_35_reg_2700[17 - 1:14], |(1'd1), res_FH_V_35_reg_2700[12:0]};

assign p_Result_34_fu_735_p4 = {res_FH_V_36_fu_659_p3[17 - 1:13], |(1'd1), res_FH_V_36_fu_659_p3[11:0]};

assign p_Result_35_fu_849_p4 = {res_FH_V_37_reg_2739[17 - 1:12], |(1'd1), res_FH_V_37_reg_2739[10:0]};

assign p_Result_36_fu_934_p4 = {res_FH_V_38_fu_858_p3[17 - 1:11], |(1'd1), res_FH_V_38_fu_858_p3[9:0]};

assign p_Result_37_fu_1048_p4 = {res_FH_V_39_reg_2778[17 - 1:10], |(1'd1), res_FH_V_39_reg_2778[8:0]};

assign p_Result_38_fu_1155_p4 = {res_FH_V_fu_1057_p3[17 - 1:9], |(1'd1), res_FH_V_fu_1057_p3[7:0]};

assign p_Result_39_fu_1349_p4 = {res_FH_V_40_reg_2817[17 - 1:8], |(1'd1), res_FH_V_40_reg_2817[6:0]};

assign p_Result_3_fu_1074_p4 = {{res_FH_V_fu_1057_p3[16:8]}};

assign p_Result_40_fu_1531_p4 = {res_FH_V_41_reg_2876[17 - 1:7], |(1'd1), res_FH_V_41_reg_2876[5:0]};

assign p_Result_41_fu_1687_p4 = {res_FH_V_42_fu_1540_p3[17 - 1:6], |(1'd1), res_FH_V_42_fu_1540_p3[4:0]};

assign p_Result_42_fu_1875_p4 = {res_FH_V_43_reg_2947[17 - 1:5], |(1'd1), res_FH_V_43_reg_2947[3:0]};

assign p_Result_43_fu_2056_p4 = {res_FH_V_44_reg_2978[17 - 1:4], |(1'd1), res_FH_V_44_reg_2978[2:0]};

assign p_Result_44_fu_2267_p4 = {res_FH_V_45_reg_3028[17 - 1:3], |(1'd1), res_FH_V_45_reg_3028[1:0]};

assign p_Result_45_fu_2454_p4 = {res_FH_V_46_reg_3087[17 - 1:2], |(1'd1), res_FH_V_46_reg_3087[0:0]};

assign p_Result_46_fu_2533_p4 = {res_FH_V_47_fu_2463_p3[17-1:1], |(1'd1)};

assign p_Result_4_fu_477_p4 = {{res_FH_V_34_fu_459_p3[16:14]}};

assign p_Result_5_fu_676_p4 = {{res_FH_V_36_fu_659_p3[16:12]}};

assign p_Result_7_fu_781_p4 = {{res_FH_V_37_fu_757_p3[16:11]}};

assign p_Result_8_fu_582_p4 = {{res_FH_V_35_fu_558_p3[16:13]}};

assign p_Result_s_96_fu_378_p4 = {{res_FH_V_33_fu_354_p3[16:15]}};

assign p_Result_s_fu_2410_p3 = x_read_reg_2637_pp0_iter9_reg[32'd17];

assign p_Val2_9_fu_362_p3 = ((and_ln318_1_fu_348_p2[0:0] == 1'b1) ? x_l_FH_V_fu_232_p3 : x_l_FH_V_26_fu_330_p2);

assign p_neg169_fu_1258_p3 = ((delta_V_fu_1246_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg170_fu_1442_p3 = ((delta_V_1_fu_1424_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg171_fu_1647_p3 = ((delta_V_2_fu_1605_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg172_fu_1838_p3 = ((delta_V_3_fu_1797_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg173_fu_1976_p3 = ((delta_V_4_fu_1970_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg174_fu_2176_p3 = ((delta_V_5_fu_2164_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign p_neg175_fu_2360_p3 = ((delta_V_6_fu_2342_p2[0:0] == 1'b1) ? 17'd131071 : 17'd0);

assign res_FH_V_31_fu_2573_p3 = ((and_ln318_24_fu_2567_p2[0:0] == 1'b1) ? res_FH_V_47_fu_2463_p3 : p_Result_46_fu_2533_p4);

assign res_FH_V_33_fu_354_p3 = ((and_ln318_1_fu_348_p2[0:0] == 1'b1) ? 17'd0 : 17'd65536);

assign res_FH_V_34_fu_459_p3 = ((and_ln318_2_reg_2693[0:0] == 1'b1) ? res_FH_V_33_reg_2667 : p_Result_31_fu_450_p4);

assign res_FH_V_35_fu_558_p3 = ((and_ln318_3_fu_552_p2[0:0] == 1'b1) ? res_FH_V_34_fu_459_p3 : p_Result_32_fu_536_p4);

assign res_FH_V_36_fu_659_p3 = ((and_ln318_4_reg_2732[0:0] == 1'b1) ? res_FH_V_35_reg_2700 : p_Result_33_fu_650_p4);

assign res_FH_V_37_fu_757_p3 = ((and_ln318_5_fu_751_p2[0:0] == 1'b1) ? res_FH_V_36_fu_659_p3 : p_Result_34_fu_735_p4);

assign res_FH_V_38_fu_858_p3 = ((and_ln318_6_reg_2771[0:0] == 1'b1) ? res_FH_V_37_reg_2739 : p_Result_35_fu_849_p4);

assign res_FH_V_39_fu_956_p3 = ((and_ln318_7_fu_950_p2[0:0] == 1'b1) ? res_FH_V_38_fu_858_p3 : p_Result_36_fu_934_p4);

assign res_FH_V_40_fu_1171_p3 = ((or_ln318_16_fu_1165_p2[0:0] == 1'b1) ? p_Result_38_fu_1155_p4 : res_FH_V_fu_1057_p3);

assign res_FH_V_41_fu_1358_p3 = ((and_ln318_10_reg_2868[0:0] == 1'b1) ? res_FH_V_40_reg_2817 : p_Result_39_fu_1349_p4);

assign res_FH_V_42_fu_1540_p3 = ((and_ln318_12_reg_2924[0:0] == 1'b1) ? res_FH_V_41_reg_2876 : p_Result_40_fu_1531_p4);

assign res_FH_V_43_fu_1727_p3 = ((and_ln318_14_fu_1721_p2[0:0] == 1'b1) ? res_FH_V_42_fu_1540_p3 : p_Result_41_fu_1687_p4);

assign res_FH_V_44_fu_1913_p3 = ((and_ln318_16_fu_1907_p2[0:0] == 1'b1) ? res_FH_V_43_reg_2947 : p_Result_42_fu_1875_p4);

assign res_FH_V_45_fu_2093_p3 = ((and_ln318_18_fu_2087_p2[0:0] == 1'b1) ? res_FH_V_44_reg_2978 : p_Result_43_fu_2056_p4);

assign res_FH_V_46_fu_2276_p3 = ((and_ln318_20_reg_3079[0:0] == 1'b1) ? res_FH_V_45_reg_3028 : p_Result_44_fu_2267_p4);

assign res_FH_V_47_fu_2463_p3 = ((and_ln318_22_reg_3136[0:0] == 1'b1) ? res_FH_V_46_reg_3087 : p_Result_45_fu_2454_p4);

assign res_FH_V_48_fu_2591_p2 = (res_FH_V_31_fu_2573_p3 + 17'd1);

assign res_FH_V_fu_1057_p3 = ((and_ln318_8_reg_2810[0:0] == 1'b1) ? res_FH_V_39_reg_2778 : p_Result_37_fu_1048_p4);

assign res_FH_l_V_fu_2585_p2 = (zext_ln712_1_fu_2581_p1 + 18'd1);

assign res_I_V_2_fu_264_p2 = (res_I_V_fu_240_p2 ^ 1'd1);

assign res_I_V_3_fu_2605_p3 = ((p_Result_27_fu_2597_p3[0:0] == 1'b1) ? res_I_V_reg_2642_pp0_iter9_reg : res_I_V_2_reg_2647_pp0_iter9_reg);

assign res_I_V_fu_240_p2 = ((x_l_I_V_52_fu_214_p4 == 2'd0) ? 1'b1 : 1'b0);

assign sext_ln235_fu_434_p1 = x_l_I_V_55_reg_2678;

assign sub_ln712_12_fu_2042_p2 = (p_neg173_reg_3023 - mul_FH_V_12_fu_1984_p4);

assign sub_ln712_15_fu_2258_p2 = (p_neg174_reg_3069 - mul_FH_V_13_reg_3053);

assign sub_ln712_18_fu_2368_p2 = (p_neg175_fu_2360_p3 - mul_FH_V_14_fu_2319_p4);

assign sub_ln712_3_fu_1450_p2 = (p_neg170_fu_1442_p3 - mul_FH_V_9_fu_1401_p4);

assign sub_ln712_6_fu_1669_p2 = (p_neg171_fu_1647_p3 - mul_FH_V_10_fu_1582_p4);

assign sub_ln712_9_fu_1858_p2 = (p_neg172_fu_1838_p3 - mul_FH_V_11_fu_1776_p4);

assign sub_ln712_fu_1340_p2 = (p_neg169_reg_2858 - mul_FH_V_8_reg_2842);

assign tmp_11_fu_2131_p4 = {{res_FH_V_45_fu_2093_p3[16:14]}};

assign tmp_12_fu_2309_p4 = {{res_FH_V_46_fu_2276_p3[16:15]}};

assign tmp_13_fu_2611_p4 = {{res_FH_V_48_fu_2591_p2[16:1]}};

assign tmp_15_fu_284_p4 = {{x_int_reg[15:14]}};

assign tmp_1_fu_2299_p4 = {{res_FH_V_46_fu_2276_p3[14:1]}};

assign tmp_2_fu_1381_p4 = {{res_FH_V_41_fu_1358_p3[9:6]}};

assign tmp_33_fu_2498_p3 = res_FH_V_47_fu_2463_p3[32'd16];

assign tmp_3_fu_1572_p4 = {{res_FH_V_42_fu_1540_p3[16:11]}};

assign tmp_4_fu_1562_p4 = {{res_FH_V_42_fu_1540_p3[10:5]}};

assign tmp_7_fu_1213_p4 = {{res_FH_V_40_fu_1171_p3[16:9]}};

assign tmp_8_fu_1942_p4 = {{res_FH_V_44_fu_1913_p3[12:3]}};

assign tmp_9_fu_1391_p4 = {{res_FH_V_41_fu_1358_p3[16:10]}};

assign tmp_fu_1203_p4 = {{res_FH_V_40_fu_1171_p3[8:7]}};

assign tmp_s_fu_2121_p4 = {{res_FH_V_45_fu_2093_p3[13:2]}};

assign trunc_ln104_fu_2486_p1 = res_FH_V_47_fu_2463_p3[15:0];

assign trunc_ln1_fu_270_p3 = {{2'd0}, {res_I_V_2_fu_264_p2}};

assign trunc_ln3_fu_2621_p3 = {{res_I_V_3_fu_2605_p3}, {tmp_13_fu_2611_p4}};

assign trunc_ln740_fu_228_p1 = x_int_reg[15:0];

assign x_l_FH_V_26_fu_330_p2 = ($signed(x_l_FH_V_fu_232_p3) + $signed(17'd98304));

assign x_l_FH_V_27_fu_416_p2 = (p_Val2_9_fu_362_p3 - mul_FH_V_fu_388_p4);

assign x_l_FH_V_28_fu_465_p3 = ((and_ln318_2_reg_2693[0:0] == 1'b1) ? p_Val2_9_reg_2673 : x_l_FH_V_27_reg_2688);

assign x_l_FH_V_29_fu_530_p2 = (x_l_FH_V_28_fu_465_p3 - mul_FH_V_1_fu_487_p5);

assign x_l_FH_V_30_fu_566_p3 = ((and_ln318_3_fu_552_p2[0:0] == 1'b1) ? x_l_FH_V_28_fu_465_p3 : x_l_FH_V_29_fu_530_p2);

assign x_l_FH_V_31_fu_627_p2 = (x_l_FH_V_30_fu_566_p3 - mul_FH_V_2_fu_592_p5);

assign x_l_FH_V_32_fu_665_p3 = ((and_ln318_4_reg_2732[0:0] == 1'b1) ? x_l_FH_V_30_reg_2706 : x_l_FH_V_31_reg_2727);

assign x_l_FH_V_33_fu_729_p2 = (x_l_FH_V_32_fu_665_p3 - mul_FH_V_3_fu_686_p5);

assign x_l_FH_V_34_fu_765_p3 = ((and_ln318_5_fu_751_p2[0:0] == 1'b1) ? x_l_FH_V_32_fu_665_p3 : x_l_FH_V_33_fu_729_p2);

assign x_l_FH_V_35_fu_826_p2 = (x_l_FH_V_34_fu_765_p3 - mul_FH_V_4_fu_791_p5);

assign x_l_FH_V_36_fu_864_p3 = ((and_ln318_6_reg_2771[0:0] == 1'b1) ? x_l_FH_V_34_reg_2745 : x_l_FH_V_35_reg_2766);

assign x_l_FH_V_37_fu_928_p2 = (x_l_FH_V_36_fu_864_p3 - mul_FH_V_5_fu_885_p5);

assign x_l_FH_V_38_fu_964_p3 = ((and_ln318_7_fu_950_p2[0:0] == 1'b1) ? x_l_FH_V_36_fu_864_p3 : x_l_FH_V_37_fu_928_p2);

assign x_l_FH_V_39_fu_1025_p2 = (x_l_FH_V_38_fu_964_p3 - mul_FH_V_6_fu_990_p5);

assign x_l_FH_V_40_fu_1063_p3 = ((and_ln318_8_reg_2810[0:0] == 1'b1) ? x_l_FH_V_38_reg_2784 : x_l_FH_V_39_reg_2805);

assign x_l_FH_V_41_fu_1149_p2 = (x_l_FH_V_40_fu_1063_p3 + xor_ln712_fu_1143_p2);

assign x_l_FH_V_42_fu_1187_p3 = ((or_ln318_16_fu_1165_p2[0:0] == 1'b1) ? x_l_FH_V_41_fu_1149_p2 : x_l_FH_V_40_fu_1063_p3);

assign x_l_FH_V_43_fu_1344_p2 = (sub_ln712_fu_1340_p2 + x_l_FH_V_42_reg_2828);

assign x_l_FH_V_44_fu_1369_p3 = ((and_ln318_10_reg_2868[0:0] == 1'b1) ? x_l_FH_V_42_reg_2828 : x_l_FH_V_43_fu_1344_p2);

assign x_l_FH_V_45_fu_1456_p2 = (sub_ln712_3_fu_1450_p2 + x_l_FH_V_44_fu_1369_p3);

assign x_l_FH_V_46_fu_1551_p3 = ((and_ln318_12_reg_2924[0:0] == 1'b1) ? x_l_FH_V_44_reg_2887 : x_l_FH_V_45_reg_2914);

assign x_l_FH_V_47_fu_1675_p2 = (sub_ln712_6_fu_1669_p2 + x_l_FH_V_46_fu_1551_p3);

assign x_l_FH_V_48_fu_1771_p3 = ((and_ln318_14_reg_2942[0:0] == 1'b1) ? x_l_FH_V_46_reg_2932 : x_l_FH_V_47_reg_2937);

assign x_l_FH_V_49_fu_1864_p2 = (sub_ln712_9_fu_1858_p2 + x_l_FH_V_48_fu_1771_p3);

assign x_l_FH_V_50_fu_1927_p3 = ((and_ln318_16_fu_1907_p2[0:0] == 1'b1) ? x_l_FH_V_48_fu_1771_p3 : x_l_FH_V_49_fu_1864_p2);

assign x_l_FH_V_51_fu_2047_p2 = (sub_ln712_12_fu_2042_p2 + x_l_FH_V_50_reg_2990);

assign x_l_FH_V_52_fu_2107_p3 = ((and_ln318_18_fu_2087_p2[0:0] == 1'b1) ? x_l_FH_V_50_reg_2990 : x_l_FH_V_51_fu_2047_p2);

assign x_l_FH_V_53_fu_2262_p2 = (sub_ln712_15_fu_2258_p2 + x_l_FH_V_52_reg_3039);

assign x_l_FH_V_54_fu_2287_p3 = ((and_ln318_20_reg_3079[0:0] == 1'b1) ? x_l_FH_V_52_reg_3039 : x_l_FH_V_53_fu_2262_p2);

assign x_l_FH_V_55_fu_2374_p2 = (sub_ln712_18_fu_2368_p2 + x_l_FH_V_54_fu_2287_p3);

assign x_l_FH_V_56_fu_2475_p3 = ((and_ln318_22_reg_3136[0:0] == 1'b1) ? x_l_FH_V_54_reg_3099 : x_l_FH_V_55_reg_3131);

assign x_l_FH_V_fu_232_p3 = {{trunc_ln740_fu_228_p1}, {1'd0}};

assign x_l_FL_V_11_fu_2184_p2 = (x_l_FL_V_20_fu_2100_p3 - mul_FL_V_5_fu_2150_p3);

assign x_l_FL_V_13_fu_2450_p2 = (x_l_FL_V_21_reg_3093 - mul_FL_V_6_reg_3111);

assign x_l_FL_V_14_fu_2469_p3 = ((and_ln318_22_reg_3136[0:0] == 1'b1) ? x_l_FL_V_21_reg_3093 : x_l_FL_V_13_fu_2450_p2);

assign x_l_FL_V_15_fu_1179_p3 = ((or_ln318_16_fu_1165_p2[0:0] == 1'b1) ? 17'd65536 : 17'd0);

assign x_l_FL_V_16_fu_1364_p3 = ((and_ln318_10_reg_2868[0:0] == 1'b1) ? x_l_FL_V_15_reg_2823 : x_l_FL_V_reg_2863);

assign x_l_FL_V_17_fu_1546_p3 = ((and_ln318_12_reg_2924[0:0] == 1'b1) ? x_l_FL_V_16_reg_2882 : x_l_FL_V_3_reg_2919);

assign x_l_FL_V_18_fu_1735_p3 = ((and_ln318_14_fu_1721_p2[0:0] == 1'b1) ? x_l_FL_V_17_fu_1546_p3 : x_l_FL_V_5_fu_1681_p2);

assign x_l_FL_V_19_fu_1920_p3 = ((and_ln318_16_fu_1907_p2[0:0] == 1'b1) ? x_l_FL_V_18_reg_2953 : x_l_FL_V_7_fu_1870_p2);

assign x_l_FL_V_20_fu_2100_p3 = ((and_ln318_18_fu_2087_p2[0:0] == 1'b1) ? x_l_FL_V_19_reg_2984 : x_l_FL_V_9_fu_2052_p2);

assign x_l_FL_V_21_fu_2282_p3 = ((and_ln318_20_reg_3079[0:0] == 1'b1) ? x_l_FL_V_20_reg_3034 : x_l_FL_V_11_reg_3074);

assign x_l_FL_V_3_fu_1462_p2 = (x_l_FL_V_16_fu_1364_p3 - mul_FL_V_1_fu_1410_p3);

assign x_l_FL_V_5_fu_1681_p2 = (x_l_FL_V_17_fu_1546_p3 - mul_FL_V_2_fu_1591_p3);

assign x_l_FL_V_7_fu_1870_p2 = (x_l_FL_V_18_reg_2953 - mul_FL_V_3_fu_1784_p3);

assign x_l_FL_V_9_fu_2052_p2 = (x_l_FL_V_19_reg_2984 - mul_FL_V_4_reg_3012);

assign x_l_FL_V_fu_1266_p2 = (x_l_FL_V_15_fu_1179_p3 - mul_FL_V_fu_1232_p3);

assign x_l_I_V_10_fu_516_p2 = ($signed(x_l_I_V_57_fu_470_p3) + $signed(5'd31));

assign x_l_I_V_13_fu_621_p2 = ($signed(x_l_I_V_59_fu_574_p3) + $signed(5'd31));

assign x_l_I_V_16_fu_715_p2 = ($signed(x_l_I_V_61_fu_670_p3) + $signed(5'd31));

assign x_l_I_V_19_fu_820_p2 = ($signed(x_l_I_V_63_fu_773_p3) + $signed(5'd31));

assign x_l_I_V_22_fu_914_p2 = ($signed(x_l_I_V_65_fu_869_p3) + $signed(5'd31));

assign x_l_I_V_25_fu_1019_p2 = ($signed(x_l_I_V_67_fu_972_p3) + $signed(5'd31));

assign x_l_I_V_28_fu_1129_p2 = ($signed(x_l_I_V_69_fu_1068_p3) + $signed(5'd31));

assign x_l_I_V_31_fu_1328_p2 = ($signed(x_l_I_V_71_reg_2835) + $signed(5'd31));

assign x_l_I_V_34_fu_1519_p2 = ($signed(x_l_I_V_73_reg_2892) + $signed(5'd31));

assign x_l_I_V_37_fu_1655_p2 = ($signed(x_l_I_V_75_fu_1556_p3) + $signed(5'd31));

assign x_l_I_V_40_fu_1846_p2 = ($signed(x_l_I_V_77_reg_2960) + $signed(5'd31));

assign x_l_I_V_43_fu_2030_p2 = ($signed(x_l_I_V_79_reg_2999) + $signed(5'd31));

assign x_l_I_V_46_fu_2246_p2 = ($signed(x_l_I_V_81_reg_3046) + $signed(5'd31));

assign x_l_I_V_49_fu_2438_p2 = ($signed(x_l_I_V_83_reg_3104) + $signed(5'd31));

assign x_l_I_V_4_fu_312_p3 = ((icmp_ln318_1_fu_294_p2[0:0] == 1'b1) ? x_l_I_V_fu_306_p2 : zext_ln235_1_fu_260_p1);

assign x_l_I_V_52_fu_214_p4 = {{x_int_reg[17:16]}};

assign x_l_I_V_53_fu_252_p3 = ((res_I_V_fu_240_p2[0:0] == 1'b1) ? zext_ln235_fu_224_p1 : p_Result_30_fu_246_p2);

assign x_l_I_V_54_fu_324_p2 = (x_l_I_V_4_fu_312_p3 - zext_ln712_fu_320_p1);

assign x_l_I_V_55_fu_370_p3 = ((and_ln318_1_fu_348_p2[0:0] == 1'b1) ? zext_ln235_1_fu_260_p1 : x_l_I_V_54_fu_324_p2);

assign x_l_I_V_56_fu_443_p3 = ((icmp_ln318_3_reg_2683[0:0] == 1'b1) ? x_l_I_V_7_fu_437_p2 : sext_ln235_fu_434_p1);

assign x_l_I_V_57_fu_470_p3 = ((and_ln318_2_reg_2693[0:0] == 1'b1) ? sext_ln235_fu_434_p1 : x_l_I_V_56_fu_443_p3);

assign x_l_I_V_58_fu_522_p3 = ((icmp_ln318_5_fu_504_p2[0:0] == 1'b1) ? x_l_I_V_10_fu_516_p2 : x_l_I_V_57_fu_470_p3);

assign x_l_I_V_59_fu_574_p3 = ((and_ln318_3_fu_552_p2[0:0] == 1'b1) ? x_l_I_V_57_fu_470_p3 : x_l_I_V_58_fu_522_p3);

assign x_l_I_V_60_fu_645_p3 = ((icmp_ln318_7_reg_2717[0:0] == 1'b1) ? x_l_I_V_13_reg_2722 : x_l_I_V_59_reg_2711);

assign x_l_I_V_61_fu_670_p3 = ((and_ln318_4_reg_2732[0:0] == 1'b1) ? x_l_I_V_59_reg_2711 : x_l_I_V_60_fu_645_p3);

assign x_l_I_V_62_fu_721_p3 = ((icmp_ln318_17_fu_703_p2[0:0] == 1'b1) ? x_l_I_V_16_fu_715_p2 : x_l_I_V_61_fu_670_p3);

assign x_l_I_V_63_fu_773_p3 = ((and_ln318_5_fu_751_p2[0:0] == 1'b1) ? x_l_I_V_61_fu_670_p3 : x_l_I_V_62_fu_721_p3);

assign x_l_I_V_64_fu_844_p3 = ((icmp_ln318_19_reg_2756[0:0] == 1'b1) ? x_l_I_V_19_reg_2761 : x_l_I_V_63_reg_2750);

assign x_l_I_V_65_fu_869_p3 = ((and_ln318_6_reg_2771[0:0] == 1'b1) ? x_l_I_V_63_reg_2750 : x_l_I_V_64_fu_844_p3);

assign x_l_I_V_66_fu_920_p3 = ((icmp_ln318_21_fu_902_p2[0:0] == 1'b1) ? x_l_I_V_22_fu_914_p2 : x_l_I_V_65_fu_869_p3);

assign x_l_I_V_67_fu_972_p3 = ((and_ln318_7_fu_950_p2[0:0] == 1'b1) ? x_l_I_V_65_fu_869_p3 : x_l_I_V_66_fu_920_p3);

assign x_l_I_V_68_fu_1043_p3 = ((icmp_ln318_23_reg_2795[0:0] == 1'b1) ? x_l_I_V_25_reg_2800 : x_l_I_V_67_reg_2789);

assign x_l_I_V_69_fu_1068_p3 = ((and_ln318_8_reg_2810[0:0] == 1'b1) ? x_l_I_V_67_reg_2789 : x_l_I_V_68_fu_1043_p3);

assign x_l_I_V_70_fu_1135_p3 = ((xor_ln331_7_fu_1123_p2[0:0] == 1'b1) ? x_l_I_V_28_fu_1129_p2 : x_l_I_V_69_fu_1068_p3);

assign x_l_I_V_71_fu_1195_p3 = ((or_ln318_16_fu_1165_p2[0:0] == 1'b1) ? x_l_I_V_70_fu_1135_p3 : x_l_I_V_69_fu_1068_p3);

assign x_l_I_V_72_fu_1333_p3 = ((and_ln331_fu_1322_p2[0:0] == 1'b1) ? x_l_I_V_71_reg_2835 : x_l_I_V_31_fu_1328_p2);

assign x_l_I_V_73_fu_1375_p3 = ((and_ln318_10_reg_2868[0:0] == 1'b1) ? x_l_I_V_71_reg_2835 : x_l_I_V_72_fu_1333_p3);

assign x_l_I_V_74_fu_1524_p3 = ((and_ln331_1_fu_1513_p2[0:0] == 1'b1) ? x_l_I_V_73_reg_2892 : x_l_I_V_34_fu_1519_p2);

assign x_l_I_V_75_fu_1556_p3 = ((and_ln318_12_reg_2924[0:0] == 1'b1) ? x_l_I_V_73_reg_2892 : x_l_I_V_74_fu_1524_p3);

assign x_l_I_V_76_fu_1661_p3 = ((and_ln331_2_fu_1641_p2[0:0] == 1'b1) ? x_l_I_V_75_fu_1556_p3 : x_l_I_V_37_fu_1655_p2);

assign x_l_I_V_77_fu_1743_p3 = ((and_ln318_14_fu_1721_p2[0:0] == 1'b1) ? x_l_I_V_75_fu_1556_p3 : x_l_I_V_76_fu_1661_p3);

assign x_l_I_V_78_fu_1851_p3 = ((and_ln331_3_fu_1832_p2[0:0] == 1'b1) ? x_l_I_V_77_reg_2960 : x_l_I_V_40_fu_1846_p2);

assign x_l_I_V_79_fu_1935_p3 = ((and_ln318_16_fu_1907_p2[0:0] == 1'b1) ? x_l_I_V_77_reg_2960 : x_l_I_V_78_fu_1851_p3);

assign x_l_I_V_7_fu_437_p2 = ($signed(sext_ln235_fu_434_p1) + $signed(5'd31));

assign x_l_I_V_80_fu_2035_p3 = ((and_ln331_4_fu_2024_p2[0:0] == 1'b1) ? x_l_I_V_79_reg_2999 : x_l_I_V_43_fu_2030_p2);

assign x_l_I_V_81_fu_2114_p3 = ((and_ln318_18_fu_2087_p2[0:0] == 1'b1) ? x_l_I_V_79_reg_2999 : x_l_I_V_80_fu_2035_p3);

assign x_l_I_V_82_fu_2251_p3 = ((and_ln331_5_fu_2240_p2[0:0] == 1'b1) ? x_l_I_V_81_reg_3046 : x_l_I_V_46_fu_2246_p2);

assign x_l_I_V_83_fu_2293_p3 = ((and_ln318_20_reg_3079[0:0] == 1'b1) ? x_l_I_V_81_reg_3046 : x_l_I_V_82_fu_2251_p3);

assign x_l_I_V_84_fu_2443_p3 = ((and_ln331_6_fu_2432_p2[0:0] == 1'b1) ? x_l_I_V_83_reg_3104 : x_l_I_V_49_fu_2438_p2);

assign x_l_I_V_85_fu_2480_p3 = ((and_ln318_22_reg_3136[0:0] == 1'b1) ? x_l_I_V_83_reg_3104 : x_l_I_V_84_fu_2443_p3);

assign x_l_I_V_fu_306_p2 = ($signed(zext_ln235_1_fu_260_p1) + $signed(4'd15));

assign xor_ln1547_1_fu_1284_p2 = (icmp_ln1547_10_fu_1278_p2 ^ 1'd1);

assign xor_ln1547_2_fu_1480_p2 = (icmp_ln1547_11_fu_1474_p2 ^ 1'd1);

assign xor_ln1547_3_fu_1709_p2 = (icmp_ln1547_12_fu_1703_p2 ^ 1'd1);

assign xor_ln1547_4_fu_1895_p2 = (icmp_ln1547_13_fu_1889_p2 ^ 1'd1);

assign xor_ln1547_5_fu_2075_p2 = (icmp_ln1547_14_fu_2070_p2 ^ 1'd1);

assign xor_ln1547_6_fu_2202_p2 = (icmp_ln1547_15_fu_2196_p2 ^ 1'd1);

assign xor_ln1547_7_fu_2392_p2 = (icmp_ln1547_16_fu_2386_p2 ^ 1'd1);

assign xor_ln1547_8_fu_2555_p2 = (icmp_ln1547_17_fu_2549_p2 ^ 1'd1);

assign xor_ln1547_fu_342_p2 = (icmp_ln1547_fu_336_p2 ^ 1'd1);

assign xor_ln1548_1_fu_1508_p2 = (icmp_ln1548_1_reg_2909 ^ 1'd1);

assign xor_ln1548_2_fu_1635_p2 = (icmp_ln1548_2_fu_1629_p2 ^ 1'd1);

assign xor_ln1548_3_fu_1826_p2 = (icmp_ln1548_3_fu_1820_p2 ^ 1'd1);

assign xor_ln1548_4_fu_2018_p2 = (icmp_ln1548_4_fu_2013_p2 ^ 1'd1);

assign xor_ln1548_5_fu_2234_p2 = (icmp_ln1548_5_fu_2230_p2 ^ 1'd1);

assign xor_ln1548_6_fu_2427_p2 = (icmp_ln1548_6_reg_3126 ^ 1'd1);

assign xor_ln1548_fu_1316_p2 = (icmp_ln1548_fu_1312_p2 ^ 1'd1);

assign xor_ln331_1_fu_1498_p2 = (delta_V_1_reg_2904 ^ 1'd1);

assign xor_ln331_2_fu_1617_p2 = (delta_V_2_fu_1605_p2 ^ 1'd1);

assign xor_ln331_3_fu_1808_p2 = (delta_V_3_fu_1797_p2 ^ 1'd1);

assign xor_ln331_4_fu_2002_p2 = (delta_V_4_reg_3017 ^ 1'd1);

assign xor_ln331_5_fu_2220_p2 = (delta_V_5_reg_3064 ^ 1'd1);

assign xor_ln331_6_fu_2417_p2 = (delta_V_6_reg_3121 ^ 1'd1);

assign xor_ln331_7_fu_1123_p2 = (icmp_ln331_fu_1117_p2 ^ 1'd1);

assign xor_ln331_fu_1302_p2 = (delta_V_reg_2853 ^ 1'd1);

assign xor_ln712_fu_1143_p2 = (mul_FH_V_7_fu_1084_p4 ^ 17'd131071);

assign zext_ln235_1_fu_260_p1 = x_l_I_V_53_fu_252_p3;

assign zext_ln235_fu_224_p1 = x_l_I_V_52_fu_214_p4;

assign zext_ln712_1_fu_2581_p1 = res_FH_V_31_fu_2573_p3;

assign zext_ln712_fu_320_p1 = trunc_ln1_fu_270_p3;

always @ (posedge ap_clk) begin
    res_FH_V_33_reg_2667[15:0] <= 16'b0000000000000000;
    p_Val2_9_reg_2673[0] <= 1'b0;
    x_l_FH_V_27_reg_2688[0] <= 1'b0;
    x_l_FH_V_30_reg_2706[0] <= 1'b0;
    x_l_FH_V_31_reg_2727[0] <= 1'b0;
    x_l_FH_V_34_reg_2745[0] <= 1'b0;
    x_l_FH_V_35_reg_2766[0] <= 1'b0;
    x_l_FH_V_38_reg_2784[0] <= 1'b0;
    x_l_FH_V_39_reg_2805[0] <= 1'b0;
    x_l_FL_V_15_reg_2823[15:0] <= 16'b0000000000000000;
    mul_FH_V_8_reg_2842[16:9] <= 8'b00000000;
    x_l_FL_V_reg_2863[14:0] <= 15'b100000000000000;
    x_l_FL_V_16_reg_2882[13:0] <= 14'b00000000000000;
    x_l_FL_V_3_reg_2919[12:0] <= 13'b1000000000000;
    x_l_FL_V_18_reg_2953[9:0] <= 10'b0000000000;
    x_l_FL_V_19_reg_2984[7:0] <= 8'b00000000;
    mul_FL_V_4_reg_3012[6:0] <= 7'b1000000;
    x_l_FL_V_20_reg_3034[5:0] <= 6'b000000;
    mul_FH_V_13_reg_3053[16:4] <= 13'b0000000000000;
    x_l_FL_V_11_reg_3074[4:0] <= 5'b10000;
    x_l_FL_V_21_reg_3093[3:0] <= 4'b0000;
    mul_FL_V_6_reg_3111[2:0] <= 3'b100;
end

endmodule //qpsk_hls_top_sqrt_fixed_18_2_s
