-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity downconvert_ip is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    rst_r : IN STD_LOGIC;
    clk : IN STD_LOGIC;
    adc_i : IN STD_LOGIC_VECTOR (15 downto 0);
    adc_q : IN STD_LOGIC_VECTOR (15 downto 0);
    lo_i : IN STD_LOGIC_VECTOR (15 downto 0);
    lo_q : IN STD_LOGIC_VECTOR (15 downto 0);
    bb_i : OUT STD_LOGIC_VECTOR (15 downto 0);
    bb_q : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of downconvert_ip is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "downconvert_ip_downconvert_ip,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z045-ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.387000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=68,HLS_SYN_LUT=61,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal sext_ln70_fu_90_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln70_reg_174 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln70_1_fu_94_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln70_2_fu_98_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln70_2_reg_186 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln70_3_fu_102_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_140_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_146_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_152_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_160_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln18_fu_124_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln70_1_fu_115_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln18_1_fu_132_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_106_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_140_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_146_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_152_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_152_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_160_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_160_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component downconvert_ip_mul_mul_16s_16s_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component downconvert_ip_mac_mulsub_16s_16s_31s_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component downconvert_ip_mac_muladd_16s_16s_31s_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;



begin
    mul_mul_16s_16s_31_4_1_U1 : component downconvert_ip_mul_mul_16s_16s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => lo_i,
        din1 => grp_fu_140_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_140_p2);

    mul_mul_16s_16s_31_4_1_U2 : component downconvert_ip_mul_mul_16s_16s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => lo_q,
        din1 => grp_fu_146_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_146_p2);

    mac_mulsub_16s_16s_31s_31_4_1_U3 : component downconvert_ip_mac_mulsub_16s_16s_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_152_p0,
        din1 => grp_fu_152_p1,
        din2 => grp_fu_140_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_152_p3);

    mac_muladd_16s_16s_31s_31_4_1_U4 : component downconvert_ip_mac_muladd_16s_16s_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_160_p0,
        din1 => grp_fu_160_p1,
        din2 => grp_fu_146_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_160_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                sext_ln70_2_reg_186 <= sext_ln70_2_fu_98_p1;
                sext_ln70_reg_174 <= sext_ln70_fu_90_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;
    bb_i <= 
        ap_const_lv16_0 when (select_ln18_1_fu_132_p0(0) = '1') else 
        trunc_ln_fu_106_p4;
    bb_q <= 
        ap_const_lv16_0 when (select_ln18_fu_124_p0(0) = '1') else 
        trunc_ln70_1_fu_115_p4;
    grp_fu_140_p1 <= sext_ln70_1_fu_94_p1(16 - 1 downto 0);
    grp_fu_146_p1 <= sext_ln70_1_fu_94_p1(16 - 1 downto 0);
    grp_fu_152_p0 <= sext_ln70_2_reg_186(16 - 1 downto 0);
    grp_fu_152_p1 <= sext_ln70_3_fu_102_p1(16 - 1 downto 0);
    grp_fu_160_p0 <= sext_ln70_reg_174(16 - 1 downto 0);
    grp_fu_160_p1 <= sext_ln70_3_fu_102_p1(16 - 1 downto 0);
    select_ln18_1_fu_132_p0 <= (0=>rst_r, others=>'-');
    select_ln18_fu_124_p0 <= (0=>rst_r, others=>'-');
        sext_ln70_1_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(adc_i),31));

        sext_ln70_2_fu_98_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lo_q),31));

        sext_ln70_3_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(adc_q),31));

        sext_ln70_fu_90_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lo_i),31));

    trunc_ln70_1_fu_115_p4 <= grp_fu_160_p3(30 downto 15);
    trunc_ln_fu_106_p4 <= grp_fu_152_p3(30 downto 15);
end behav;
